import { spawn, type ChildProcessWithoutNullStreams } from 'node:child_process';
import { createHash, randomBytes } from 'node:crypto';
import { lstatSync, readFileSync, realpathSync } from 'node:fs';
import { lstat, readFile, realpath, unlink, writeFile } from 'node:fs/promises';
import { createConnection, type Socket } from 'node:net';
import { dirname, isAbsolute, join, relative, resolve, sep } from 'node:path';
import { createInterface } from 'node:readline';

import { canonicalJson } from './artifacts.ts';
import type { Sha256 } from './batch.ts';
import {
  F005_NATIVE_GUARD_PINS,
  resolveF005NativeGuardExecutable,
  type F005NativeFileIdentity,
} from './f005-source.ts';
import type {
  F005CapacityRecorderBackend,
  F005CapacityPhase,
  F005MutationNotice,
  F005MutationObservation,
  F005TemporaryWriteLease,
} from './f005-voice.ts';
import type {
  F005AcceptanceCapacityBackend,
  F005AcceptanceMutationNotice,
  F005AcceptanceMutationObservation,
} from './f005-acceptance.ts';

const SHA256 = /^[0-9a-f]{64}$/u;
const NATIVE_FILE_IDENTITY = /^[0-9a-f]{8}:[0-9a-f]{16}$/u;
const SAFE_PATH = /^(?!\/)(?!.*(?:^|\/)\.\.?\/)(?!.*[\\:\0])[\p{L}\p{N}._/-]+$/u;
const PHASES = new Set(['voice', 'preview', 'accept', 'build']);
const WORK_IDS = new Set(['000799', '001076', '001104']);
const mintedNativeBackends = new WeakSet<object>();

type F005SystemSetInfoPathBucket =
  | 'CACHE' | 'CONTENT' | 'DATA' | 'DIST' | 'NATIVE'
  | 'NODE_MODULES' | 'PUBLIC' | 'SCRIPTS' | 'SRC' | 'OTHER';
type F005SystemSetInfoExtensionBucket =
  | 'EXE' | 'JS' | 'JSON' | 'LOG' | 'TMP' | 'TS' | 'WAV' | 'OTHER';
type F005SystemSetInfoEntryState = 'FILE' | 'DIRECTORY' | 'ABSENT';
type F005SystemSetInfoLeaseState =
  | 'NO_LEASE'
  | 'BOUND_LEASE'
  | 'UNBOUND_LEASE'
  | 'DONE_ID'
  | 'DONE_CHANGED'
  | 'DONE_MISSING';
export type F005SystemSetInfoDiagnosticCode =
  `F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_SETINFO_UNKNOWN_PATH_${F005SystemSetInfoPathBucket}_${F005SystemSetInfoExtensionBucket}_${F005SystemSetInfoEntryState}_${F005SystemSetInfoLeaseState}`;
type F005SystemSetInfoCorrelationStage =
  | 'CREATE_BIND_MISMATCH'
  | 'CREATE_SNAPSHOT_MISSING'
  | 'CURRENT_MISSING'
  | 'DEFERRED_BIND_MISMATCH'
  | 'DEFERRED_CLEANUP'
  | 'DEFERRED_SNAPSHOT_MISSING'
  | 'DEFERRED_TUPLE_MISMATCH'
  | 'FILE_OBJECT_MISMATCH'
  | 'IDENTITY_MISMATCH'
  | 'LEASE_CLOSED'
  | 'LEASE_SNAPSHOT_MISSING'
  | 'RENAME_CONSUME';
export type F005SystemSetInfoCorrelationDiagnosticCode =
  `F005_ETW_SYSTEM_SETINFO_CORRELATION_${F005SystemSetInfoCorrelationStage}`;
type F005CompletedWriteRejoinStage =
  | 'AUTH_FAILURE'
  | 'SYSTEM_PID'
  | 'EVENT'
  | 'FILE_OBJECT_ZERO'
  | 'PHASE'
  | 'BEFORE_RESERVATION'
  | 'AFTER_COMPLETION_WITHIN_100MS'
  | 'AFTER_COMPLETION_WITHIN_500MS'
  | 'AFTER_COMPLETION_WITHIN_2S'
  | 'AFTER_COMPLETION_WITHIN_10S'
  | 'AFTER_COMPLETION_OVER_10S'
  | 'FILE_OBJECT_BINDING'
  | 'CURRENT_MISSING'
  | 'IDENTITY_MISMATCH';
export type F005CompletedWriteRejoinDiagnosticCode =
  `F005_ETW_COMPLETED_WRITE_REJOIN_${F005CompletedWriteRejoinStage}`;
type F005ClosedLeaseRejoinStage =
  | 'SNAPSHOT_MISSING'
  | 'FILE_OBJECT_BINDING'
  | 'CURRENT_MISSING'
  | 'IDENTITY_MISMATCH'
  | 'CANDIDATE';
export type F005ClosedLeaseRejoinDiagnosticCode =
  `F005_ETW_CLOSED_LEASE_REJOIN_${F005ClosedLeaseRejoinStage}`;
type F005SystemUnboundWriteStage =
  | 'FILE_OBJECT_ZERO'
  | 'LEASE_SNAPSHOT_MISSING'
  | 'LEASE_CURRENT_MISSING'
  | 'LEASE_IDENTITY_MISMATCH'
  | 'LEASE_OPEN_CANDIDATE'
  | 'LEASE_CLOSED_CANDIDATE'
  | 'COMPLETED_ID'
  | 'COMPLETED_CHANGED'
  | 'COMPLETED_MISSING'
  | 'OTHER_KNOWN_PATH';
export type F005SystemUnboundWriteDiagnosticCode =
  `F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_WRITE_KNOWN_PATH_${F005SystemUnboundWriteStage}`;
export type F005SystemUnboundWriteOtherKnownPathDiagnosticCode =
  `F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_UNBOUND_WRITE_OTHER_KNOWN_PATH_${F005SystemSetInfoPathBucket}_${F005SystemSetInfoExtensionBucket}_${F005SystemSetInfoEntryState}_${F005SystemSetInfoLeaseState}`;
type F005SystemDirectoryWriteRejoinStage =
  | 'SNAPSHOT_MISSING'
  | 'CURRENT_MISSING'
  | 'IDENTITY_MISMATCH'
  | 'OWNER_MISSING'
  | 'ROOT_INACTIVE'
  | 'CANDIDATE';
export type F005SystemDirectoryWriteRejoinDiagnosticCode =
  `F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_DIRECTORY_WRITE_REJOIN_${F005SystemDirectoryWriteRejoinStage}`;
type F005SystemDirectoryActiveLeaseWriteRejoinStage =
  | 'DIRECTORY_SNAPSHOT_MISSING'
  | 'DIRECTORY_CURRENT_MISSING'
  | 'DIRECTORY_IDENTITY_MISMATCH'
  | 'DIRECTORY_OWNER_MISSING'
  | 'DIRECTORY_ROOT_INACTIVE'
  | 'DIRECTORY_UNKNOWN'
  | 'LEASE_MISSING'
  | 'LEASE_PHASE'
  | 'LEASE_PARENT'
  | 'LEASE_BOUND'
  | 'LEASE_CLOSED'
  | 'LEASE_ESCAPE'
  | 'CANDIDATE';
export type F005SystemDirectoryActiveLeaseWriteRejoinDiagnosticCode =
  `F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_DIRECTORY_ACTIVE_LEASE_WRITE_REJOIN_${F005SystemDirectoryActiveLeaseWriteRejoinStage}`;
type F005SystemDirectoryBoundLeaseWriteRejoinStage =
  | 'DIRECTORY_SNAPSHOT_MISSING'
  | 'DIRECTORY_CURRENT_MISSING'
  | 'DIRECTORY_IDENTITY_MISMATCH'
  | 'DIRECTORY_OWNER_MISSING'
  | 'DIRECTORY_ROOT_INACTIVE'
  | 'DIRECTORY_UNKNOWN'
  | 'LEASE_MISSING'
  | 'LEASE_PHASE'
  | 'LEASE_PARENT'
  | 'LEASE_CLOSED'
  | 'LEASE_UNBOUND'
  | 'LEASE_SNAPSHOT_MISSING'
  | 'LEASE_BINDING_MISSING'
  | 'LEASE_BINDING_MISMATCH'
  | 'LEASE_CURRENT_MISSING'
  | 'LEASE_IDENTITY_MISMATCH'
  | 'LEASE_ESCAPE'
  | 'CANDIDATE';
export type F005SystemDirectoryBoundLeaseWriteRejoinDiagnosticCode =
  `F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_DIRECTORY_BOUND_LEASE_WRITE_REJOIN_${F005SystemDirectoryBoundLeaseWriteRejoinStage}`;
type F005SystemDirectoryBoundLeaseRenameWriteRejoinStage =
  | 'PATH_MISSING'
  | 'PARENT'
  | 'RESERVATION_MISSING'
  | 'BEFORE_LEASE_RESERVATION'
  | 'AFTER_LEASE_RESERVATION'
  | 'CURRENT_MISSING'
  | 'IDENTITY_MISMATCH'
  | 'LEASE_ESCAPE'
  | 'CANDIDATE';
export type F005SystemDirectoryBoundLeaseRenameWriteRejoinDiagnosticCode =
  `F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_DIRECTORY_BOUND_LEASE_RENAME_WRITE_REJOIN_${F005SystemDirectoryBoundLeaseRenameWriteRejoinStage}`;
type F005AfterLeaseReservationDirectoryRejoinFailureStage =
  | 'TUPLE_INSPECTION_FAILED'
  | 'PROCESS_WAIT_FAILED'
  | 'PROCESS_IDENTITY_FAILED'
  | 'JOB_QUERY_FAILED'
  | 'PROCESS_OUTSIDE_JOB'
  | 'DIRECTORY_IDENTITY_MISMATCH'
  | 'LEASE_CURRENT_EXISTS'
  | 'TARGET_IDENTITY_MISMATCH'
  | 'BINDING_MISMATCH';
export type F005AfterLeaseReservationDirectoryRejoinFailureCode =
  `F005_ETW_SYSTEM_DIRECTORY_AFTER_LEASE_REJOIN_${F005AfterLeaseReservationDirectoryRejoinFailureStage}`;
type F005SystemDirectoryBoundLeaseRejoinFailureStage =
  | 'INITIAL_TUPLE_INSPECTION_FAILED'
  | 'PROCESS_IDENTITY_FAILED'
  | 'PROCESS_WAIT_FAILED'
  | 'JOB_QUERY_FAILED'
  | 'PROCESS_TUPLE_MISMATCH'
  | 'PROCESS_SIGNALED'
  | 'PROCESS_OUTSIDE_JOB'
  | 'ACTIVE_LEASE_CHANGED'
  | 'EVENT_FILE_OBJECT_BOUND'
  | 'RENAME_STATE_CHANGED'
  | 'DIRECTORY_IDENTITY_MISMATCH'
  | 'LEASE_CURRENT_IDENTITY_MISMATCH'
  | 'BINDING_MISMATCH'
  | 'PROCESS_RECHECK_IDENTITY_FAILED'
  | 'PROCESS_RECHECK_WAIT_FAILED'
  | 'PROCESS_RECHECK_JOB_QUERY_FAILED'
  | 'PROCESS_RECHECK_TUPLE_MISMATCH'
  | 'PROCESS_RECHECK_SIGNALED'
  | 'PROCESS_RECHECK_OUTSIDE_JOB';
export type F005SystemDirectoryBoundLeaseRejoinFailureCode =
  `F005_ETW_SYSTEM_DIRECTORY_BOUND_LEASE_REJOIN_${F005SystemDirectoryBoundLeaseRejoinFailureStage}`;
export const F005_WRITE_COMPLETION_DRAIN_FAILURE_STAGES = Object.freeze([
  'PREPARE_TUPLE_MISMATCH',
  'PROCESS_IDENTITY_FAILED',
  'PROCESS_WAIT_FAILED',
  'JOB_QUERY_FAILED',
  'PROCESS_TUPLE_MISMATCH',
  'PROCESS_SIGNALED',
  'PROCESS_OUTSIDE_JOB',
  'EVENT_TUPLE_MISMATCH',
  'EVENT_TUPLE_LOOKUP_EPOCH_EMPTY_NO_LATE_PROOF',
  'EVENT_TUPLE_LOOKUP_EPOCH_EMPTY_AT_OR_BEFORE_RESERVATION_ALL',
  'EVENT_TUPLE_LOOKUP_EPOCH_EMPTY_POST_UPPER_PROOF_MISSING_ALL',
  'EVENT_TUPLE_LOOKUP_EPOCH_EMPTY_POST_UPPER_PROOF_LEDGER_UNAVAILABLE_ALL',
  'EVENT_TUPLE_LOOKUP_EPOCH_EMPTY_POST_UPPER_PROOF_CURRENT_FILE_OBJECT_MISMATCH_ALL',
  'EVENT_TUPLE_LOOKUP_EPOCH_EMPTY_POST_UPPER_PROOF_CURRENT_BINDING_MISMATCH_ALL',
  'EVENT_TUPLE_LOOKUP_EPOCH_EMPTY_POST_UPPER_PROOF_CURRENT_BINDING_ENTRY_MISSING_ALL',
  'EVENT_TUPLE_LOOKUP_EPOCH_EMPTY_POST_UPPER_PROOF_CURRENT_BINDING_GENERATION_MISMATCH_ALL',
  'EVENT_TUPLE_LOOKUP_EPOCH_EMPTY_POST_UPPER_PROOF_CURRENT_BINDING_IDENTITY_MISMATCH_ALL',
  'EVENT_TUPLE_LOOKUP_EPOCH_EMPTY_POST_UPPER_PROOF_CURRENT_BINDING_PATH_MISMATCH_ALL',
  'EVENT_TUPLE_LOOKUP_EPOCH_EMPTY_POST_UPPER_PROOF_CURRENT_BINDING_STATE_NOT_BOUND_ALL',
  'EVENT_TUPLE_LOOKUP_EPOCH_EMPTY_POST_UPPER_PROOF_CURRENT_BINDING_STATE_NOT_BOUND_OR_RETIRED_ALL',
  'EVENT_TUPLE_LOOKUP_EPOCH_EMPTY_POST_UPPER_PROOF_CURRENT_BINDING_MIXED',
  'EVENT_TUPLE_LOOKUP_EPOCH_EMPTY_POST_UPPER_PROOF_PARENT_NOT_UNBOUND_ALL',
  'EVENT_TUPLE_LOOKUP_EPOCH_EMPTY_POST_UPPER_PROOF_PARENT_BOUND_ALL',
  'EVENT_TUPLE_LOOKUP_EPOCH_EMPTY_POST_UPPER_PROOF_PARENT_RETIRED_ALL',
  'EVENT_TUPLE_LOOKUP_EPOCH_EMPTY_POST_UPPER_PROOF_PARENT_OTHER_STATE_ALL',
  'EVENT_TUPLE_LOOKUP_EPOCH_EMPTY_POST_UPPER_PROOF_PARENT_STATE_MIXED',
  'EVENT_TUPLE_LOOKUP_EPOCH_EMPTY_POST_UPPER_PROOF_PARENT_BOUND_ACTIVE_LEASE_WRITE_ALL',
  'EVENT_TUPLE_LOOKUP_EPOCH_EMPTY_POST_UPPER_PROOF_PARENT_BOUND_ACTIVE_LEASE_SETINFO_ALL',
  'EVENT_TUPLE_LOOKUP_EPOCH_EMPTY_POST_UPPER_PROOF_PARENT_BOUND_ACTIVE_LEASE_BINDING_MISMATCH_ALL',
  'EVENT_TUPLE_LOOKUP_EPOCH_EMPTY_POST_UPPER_PROOF_PARENT_BOUND_CONTEXT_MISSING',
  'EVENT_TUPLE_LOOKUP_EPOCH_EMPTY_POST_UPPER_PROOF_PARENT_BOUND_TUPLE_INVALID',
  'EVENT_TUPLE_LOOKUP_EPOCH_EMPTY_POST_UPPER_PROOF_PARENT_BOUND_PHASE_MISMATCH',
  'EVENT_TUPLE_LOOKUP_EPOCH_EMPTY_POST_UPPER_PROOF_PARENT_BOUND_PARENT_MISMATCH',
  'EVENT_TUPLE_LOOKUP_EPOCH_EMPTY_POST_UPPER_PROOF_PARENT_BOUND_RESERVATION_ORDER',
  'EVENT_TUPLE_LOOKUP_EPOCH_EMPTY_POST_UPPER_PROOF_PARENT_BOUND_EVENT_FO_MISMATCH',
  'EVENT_TUPLE_LOOKUP_EPOCH_EMPTY_POST_UPPER_PROOF_PARENT_BOUND_LEDGER_MISSING',
  'EVENT_TUPLE_LOOKUP_EPOCH_EMPTY_POST_UPPER_PROOF_MIXED',
  'EVENT_TUPLE_LOOKUP_EPOCH_EMPTY_TIME_PROOF_MIXED',
  'EVENT_TUPLE_LOOKUP_EXACT_MISSING',
  'EVENT_TUPLE_LOOKUP_EXACT_AMBIGUOUS',
  'EVENT_TUPLE_RECHECK_SEAL_MISSING',
  'EVENT_TUPLE_RECHECK_SEAL_AMBIGUOUS',
  'EVENT_TUPLE_RECHECK_FIELDS',
  'EVENT_IDENTITY_FAILED',
  'BUFFER_LIMIT',
  'FAILED',
  'TIMEOUT',
  'STATE_CHANGED',
  'DIRECTORY_IDENTITY_MISMATCH',
  'CURRENT_IDENTITY_MISMATCH',
  'BINDING_MISMATCH',
  'RECHECK_PROCESS_IDENTITY_FAILED',
  'RECHECK_PROCESS_WAIT_FAILED',
  'RECHECK_PROCESS_TUPLE_MISMATCH',
  'RECHECK_PROCESS_NOT_SIGNALED',
  'LATE_EVENT_AFTER_SEAL',
  'LATE_RETAINED_PARENT_OTHER_ACTIVE_SAME_PARENT_POST_RESERVATION_WRITE',
  'LATE_RETAINED_PARENT_OTHER_ACTIVE_SAME_PARENT_POST_RESERVATION_SETINFO',
  'LATE_DIAG_WRITE_SEAL_NOT_COMPLETED_RETAINED',
  'LATE_DIAG_WRITE_CURRENT_PATH',
  'LATE_DIAG_WRITE_ACTIVE_LEASE_MISSING',
  'LATE_DIAG_WRITE_ACTIVE_PARENT_MISMATCH',
  'LATE_DIAG_WRITE_AT_OR_BEFORE_ACTIVE_RESERVATION',
  'LATE_DIAG_WRITE_MIXED_CAUSES',
  'LATE_DIAG_WRITE_ACTIVE_PRODUCER_RECORD_MISSING',
  'LATE_DIAG_WRITE_ACTIVE_PRODUCER_TUPLE_MISMATCH',
  'LATE_DIAG_WRITE_AT_OR_BEFORE_ACTIVE_PRODUCER_BIRTH',
  'LATE_DIAG_WRITE_AFTER_ACTIVE_PRODUCER_BIRTH',
  'LATE_DIAG_WRITE_ACTIVE_PRODUCER_RESERVATION_BIRTH_RECORD_MISSING',
  'LATE_DIAG_WRITE_ACTIVE_PRODUCER_RESERVATION_BIRTH_TUPLE_MISMATCH',
  'LATE_DIAG_WRITE_ACTIVE_PRODUCER_AT_OR_BEFORE_RESERVATION_BIRTH',
  'LATE_DIAG_WRITE_ACTIVE_PRODUCER_AFTER_RESERVATION_BIRTH',
  'LATE_DIAG_WRITE_ACTIVE_PRODUCER_AFTER_RESERVATION_BIRTH_AT_OR_BEFORE_INITIAL',
  'LATE_DIAG_WRITE_ACTIVE_PRODUCER_AFTER_RESERVATION_BIRTH_AFTER_INITIAL_TO_CURRENT',
  'LATE_DIAG_WRITE_ACTIVE_PRODUCER_RESERVATION_STATE_ACTIVE_PHASE_CHANGED',
  'LATE_DIAG_WRITE_ACTIVE_PRODUCER_RESERVATION_STATE_CURRENT_BEFORE_INITIAL',
  'LATE_DIAG_SETINFO_SEAL_NOT_COMPLETED_RETAINED',
  'LATE_DIAG_SETINFO_CURRENT_PATH',
  'LATE_DIAG_SETINFO_ACTIVE_LEASE_MISSING',
  'LATE_DIAG_SETINFO_ACTIVE_PARENT_MISMATCH',
  'LATE_DIAG_SETINFO_AT_OR_BEFORE_ACTIVE_RESERVATION',
  'LATE_DIAG_SETINFO_MIXED_CAUSES',
  'COMPLETED_NO_LEASE_DIRECTORY_HANDOFF_CANDIDATE_AMBIGUOUS',
  'COMPLETED_NO_LEASE_DIRECTORY_HANDOFF_IDENTITY_MATCH_NONE',
  'COMPLETED_NO_LEASE_DIRECTORY_HANDOFF_IDENTITY_MATCH_AMBIGUOUS',
  'ACTIVE_DIRECTORY_HANDOFF_CANDIDATE_AMBIGUOUS',
  'ACTIVE_DIRECTORY_HANDOFF_ELIGIBLE_EXACT_ONE',
  'ACTIVE_DIRECTORY_HANDOFF_ELIGIBLE_AMBIGUOUS',
  'ACTIVE_DIRECTORY_HANDOFF_ELIGIBLE_ALL',
  'ACTIVE_DIRECTORY_HANDOFF_ELIGIBLE_MIXED',
] as const);
type F005WriteCompletionDrainFailureStage =
  typeof F005_WRITE_COMPLETION_DRAIN_FAILURE_STAGES[number];
export type F005WriteCompletionDrainFailureCode =
  `F005_ETW_WRITE_COMPLETION_DRAIN_${F005WriteCompletionDrainFailureStage}`;
export const F005_WRITE_LEASE_PRODUCER_BIRTH_FAILURE_STAGES = Object.freeze([
  'TIMEOUT',
  'TUPLE_MISMATCH',
  'PROCESS_IDENTITY_FAILED',
  'STATE_CHANGED',
] as const);
type F005WriteLeaseProducerBirthFailureStage =
  typeof F005_WRITE_LEASE_PRODUCER_BIRTH_FAILURE_STAGES[number];
export type F005WriteLeaseProducerBirthFailureCode =
  `F005_WRITE_LEASE_PRODUCER_BIRTH_${F005WriteLeaseProducerBirthFailureStage}`;

export function isF005WriteLeaseProducerBirthFailureCode(
  value: unknown,
): value is F005WriteLeaseProducerBirthFailureCode {
  return typeof value === 'string' && value.length <= 127 &&
    F005_WRITE_LEASE_PRODUCER_BIRTH_FAILURE_STAGES.some(
      (stage) => value === `F005_WRITE_LEASE_PRODUCER_BIRTH_${stage}`,
    );
}
type F005SystemBoundFileObjectRejoinStage =
  | 'SNAPSHOT_MISSING'
  | 'PATH_MISMATCH'
  | 'CURRENT_MISSING'
  | 'IDENTITY_MISMATCH'
  | 'LEASE_MISSING'
  | 'LEASE_PHASE'
  | 'LEASE_BINDING'
  | 'LEASE_CLOSED'
  | 'LEASE_ESCAPE'
  | 'NO_PENDING_FILE'
  | 'NO_PENDING_OTHER'
  | 'NO_PENDING_DIR_SNAPSHOT_MISSING'
  | 'NO_PENDING_DIR_CURRENT_MISSING'
  | 'NO_PENDING_DIR_ID_MISMATCH'
  | 'NO_PENDING_DIR_OWNER_MISSING'
  | 'NO_PENDING_DIR_ROOT_INACTIVE'
  | 'NO_PENDING_DIR_UNKNOWN'
  | 'NO_PENDING_LEASE_PARENT'
  | 'NO_PENDING_LEASE_CLOSED'
  | 'NO_PENDING_LEASE_SNAPSHOT_MISSING'
  | 'NO_PENDING_LEASE_BINDING_MISSING'
  | 'NO_PENDING_LEASE_BINDING_MISMATCH'
  | 'NO_PENDING_LEASE_CURRENT_MISSING'
  | 'NO_PENDING_LEASE_ID_MISMATCH'
  | 'NO_PENDING_LEASE_ESCAPE'
  | 'NO_PENDING_CANDIDATE'
  | 'NO_PENDING_STATE_DRIFT'
  | 'NO_PENDING_UNBOUND_SNAPSHOT_PRESENT'
  | 'NO_PENDING_UNBOUND_BEFORE_RESERVATION'
  | 'NO_PENDING_UNBOUND_CURRENT_INSPECTION_FAILED'
  | 'NO_PENDING_UNBOUND_CURRENT_MISSING'
  | 'NO_PENDING_UNBOUND_DEFERRED_MISSING'
  | 'NO_PENDING_UNBOUND_DEFERRED_TUPLE'
  | 'NO_PENDING_UNBOUND_CURRENT_ID_MISMATCH'
  | 'NO_PENDING_UNBOUND_PROCESS_WAIT_FAILED'
  | 'NO_PENDING_UNBOUND_PROCESS_IDENTITY_FAILED'
  | 'NO_PENDING_UNBOUND_JOB_QUERY_FAILED'
  | 'NO_PENDING_UNBOUND_PROCESS_TUPLE'
  | 'NO_PENDING_UNBOUND_PROCESS_SIGNALED'
  | 'NO_PENDING_UNBOUND_LEASE_ESCAPE'
  | 'NO_PENDING_UNBOUND_CANDIDATE'
  | 'CANDIDATE';
export type F005SystemBoundFileObjectRejoinDiagnosticCode =
  `F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_BOUND_FILE_OBJECT_REJOIN_${F005SystemBoundFileObjectRejoinStage}`;
type F005SystemBoundFileObjectRenameLeasePathRejoinStage =
  | 'TARGET_MISMATCH'
  | 'RESERVATION_MISSING'
  | 'RESERVATION_ORDER'
  | 'BEFORE_LEASE_RESERVATION'
  | 'AFTER_LEASE_RESERVATION'
  | 'LEASE_CURRENT_EXISTS'
  | 'SNAPSHOT_MISSING'
  | 'SNAPSHOT_PATH'
  | 'IDENTITY_MISMATCH'
  | 'BINDING_MISMATCH'
  | 'LEASE_CLOSED'
  | 'LEASE_ESCAPE'
  | 'CANDIDATE';
export type F005SystemBoundFileObjectRenameLeasePathRejoinDiagnosticCode =
  `F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_BOUND_FILE_OBJECT_REJOIN_RENAME_LEASE_PATH_${F005SystemBoundFileObjectRenameLeasePathRejoinStage}`;

const F005_NATIVE_SYSTEM_SETINFO_DIAGNOSTIC = new RegExp(
  '^ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_SETINFO_UNKNOWN_PATH_' +
  '(?:CACHE|CONTENT|DATA|DIST|NATIVE|NODE_MODULES|PUBLIC|SCRIPTS|SRC|OTHER)_' +
  '(?:EXE|JS|JSON|LOG|TMP|TS|WAV|OTHER)_' +
  '(?:FILE|DIRECTORY|ABSENT)_' +
  '(?:NO_LEASE|BOUND_LEASE|UNBOUND_LEASE|DONE_ID|DONE_CHANGED|DONE_MISSING)$',
  'u',
);
const F005_NATIVE_SYSTEM_SETINFO_CORRELATION_DIAGNOSTIC = new RegExp(
  '^ETW_SYSTEM_SETINFO_CORRELATION_' +
  '(?:CREATE_BIND_MISMATCH|CREATE_SNAPSHOT_MISSING|CURRENT_MISSING|' +
  'DEFERRED_BIND_MISMATCH|DEFERRED_CLEANUP|DEFERRED_SNAPSHOT_MISSING|' +
  'DEFERRED_TUPLE_MISMATCH|FILE_OBJECT_MISMATCH|IDENTITY_MISMATCH|' +
  'LEASE_CLOSED|LEASE_SNAPSHOT_MISSING|RENAME_CONSUME)$',
  'u',
);
const F005_NATIVE_COMPLETED_WRITE_REJOIN_DIAGNOSTIC = new RegExp(
  '^ETW_COMPLETED_WRITE_REJOIN_' +
  '(?:AUTH_FAILURE|SYSTEM_PID|EVENT|FILE_OBJECT_ZERO|PHASE|' +
  'BEFORE_RESERVATION|AFTER_COMPLETION_(?:WITHIN_100MS|WITHIN_500MS|' +
  'WITHIN_2S|WITHIN_10S|OVER_10S)|FILE_OBJECT_BINDING|' +
  'CURRENT_MISSING|IDENTITY_MISMATCH)$',
  'u',
);
const F005_NATIVE_CLOSED_LEASE_REJOIN_DIAGNOSTIC = new RegExp(
  '^ETW_CLOSED_LEASE_REJOIN_' +
  '(?:SNAPSHOT_MISSING|FILE_OBJECT_BINDING|CURRENT_MISSING|' +
  'IDENTITY_MISMATCH|CANDIDATE)$',
  'u',
);
const F005_NATIVE_SYSTEM_UNBOUND_WRITE_DIAGNOSTIC = new RegExp(
  '^ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_WRITE_KNOWN_PATH_' +
  '(?:FILE_OBJECT_ZERO|LEASE_(?:SNAPSHOT_MISSING|CURRENT_MISSING|' +
  'IDENTITY_MISMATCH|OPEN_CANDIDATE|CLOSED_CANDIDATE)|' +
  'COMPLETED_(?:ID|CHANGED|MISSING)|OTHER_KNOWN_PATH)$',
  'u',
);
const F005_NATIVE_SYSTEM_UNBOUND_WRITE_OTHER_KNOWN_PATH_DIAGNOSTIC = new RegExp(
  '^ETW_PID_NOT_JOB_MEMBER_SYSTEM_UNBOUND_WRITE_OTHER_KNOWN_PATH_' +
  '(?:CACHE|CONTENT|DATA|DIST|NATIVE|NODE_MODULES|PUBLIC|SCRIPTS|SRC|OTHER)_' +
  '(?:EXE|JS|JSON|LOG|TMP|TS|WAV|OTHER)_' +
  '(?:FILE|DIRECTORY|ABSENT)_' +
  '(?:NO_LEASE|BOUND_LEASE|UNBOUND_LEASE|DONE_ID|DONE_CHANGED|DONE_MISSING)$',
  'u',
);
const F005_NATIVE_SYSTEM_DIRECTORY_WRITE_REJOIN_DIAGNOSTIC = new RegExp(
  '^ETW_PID_NOT_JOB_MEMBER_SYSTEM_DIRECTORY_WRITE_REJOIN_' +
  '(?:SNAPSHOT_MISSING|CURRENT_MISSING|IDENTITY_MISMATCH|' +
  'OWNER_MISSING|ROOT_INACTIVE|CANDIDATE)$',
  'u',
);
const F005_NATIVE_SYSTEM_DIRECTORY_ACTIVE_LEASE_WRITE_REJOIN_DIAGNOSTIC =
  new RegExp(
    '^ETW_PID_NOT_JOB_MEMBER_SYSTEM_DIRECTORY_ACTIVE_LEASE_WRITE_REJOIN_' +
    '(?:DIRECTORY_(?:SNAPSHOT_MISSING|CURRENT_MISSING|IDENTITY_MISMATCH|' +
    'OWNER_MISSING|ROOT_INACTIVE|UNKNOWN)|LEASE_(?:MISSING|PHASE|PARENT|' +
    'BOUND|CLOSED|ESCAPE)|CANDIDATE)$',
    'u',
  );
const F005_NATIVE_SYSTEM_DIRECTORY_BOUND_LEASE_WRITE_REJOIN_DIAGNOSTIC =
  new RegExp(
    '^ETW_PID_NOT_JOB_MEMBER_SYSTEM_DIRECTORY_BOUND_LEASE_WRITE_REJOIN_' +
    '(?:DIRECTORY_(?:SNAPSHOT_MISSING|CURRENT_MISSING|IDENTITY_MISMATCH|' +
    'OWNER_MISSING|ROOT_INACTIVE|UNKNOWN)|LEASE_(?:MISSING|PHASE|PARENT|' +
    'CLOSED|UNBOUND|SNAPSHOT_MISSING|BINDING_(?:MISSING|MISMATCH)|' +
    'CURRENT_MISSING|IDENTITY_MISMATCH|ESCAPE)|CANDIDATE)$',
    'u',
  );
const F005_NATIVE_SYSTEM_DIRECTORY_BOUND_LEASE_RENAME_WRITE_REJOIN_DIAGNOSTIC =
  new RegExp(
    '^ETW_PID_NOT_JOB_MEMBER_SYSTEM_DIRECTORY_BOUND_LEASE_RENAME_WRITE_REJOIN_' +
    '(?:PATH_MISSING|PARENT|RESERVATION_MISSING|' +
    'BEFORE_LEASE_RESERVATION|AFTER_LEASE_RESERVATION|' +
    'CURRENT_MISSING|IDENTITY_MISMATCH|LEASE_ESCAPE|CANDIDATE)$',
    'u',
  );
const F005_NATIVE_AFTER_LEASE_RESERVATION_DIRECTORY_REJOIN_FAILURE = new RegExp(
  '^ETW_SYSTEM_DIRECTORY_AFTER_LEASE_REJOIN_' +
  '(?:TUPLE_INSPECTION_FAILED|PROCESS_WAIT_FAILED|PROCESS_IDENTITY_FAILED|' +
  'JOB_QUERY_FAILED|PROCESS_OUTSIDE_JOB|DIRECTORY_IDENTITY_MISMATCH|' +
  'LEASE_CURRENT_EXISTS|TARGET_IDENTITY_MISMATCH|BINDING_MISMATCH)$',
  'u',
);
const F005_NATIVE_SYSTEM_DIRECTORY_BOUND_LEASE_REJOIN_FAILURE = new RegExp(
  '^ETW_SYSTEM_DIRECTORY_BOUND_LEASE_REJOIN_(?:' +
  'INITIAL_TUPLE_INSPECTION_FAILED|PROCESS_IDENTITY_FAILED|' +
  'PROCESS_WAIT_FAILED|JOB_QUERY_FAILED|PROCESS_TUPLE_MISMATCH|' +
  'PROCESS_SIGNALED|PROCESS_OUTSIDE_JOB|ACTIVE_LEASE_CHANGED|' +
  'EVENT_FILE_OBJECT_BOUND|RENAME_STATE_CHANGED|' +
  'DIRECTORY_IDENTITY_MISMATCH|LEASE_CURRENT_IDENTITY_MISMATCH|' +
  'BINDING_MISMATCH|PROCESS_RECHECK_(?:IDENTITY_FAILED|WAIT_FAILED|' +
  'JOB_QUERY_FAILED|TUPLE_MISMATCH|SIGNALED|OUTSIDE_JOB))$',
  'u',
);
const F005_WRITE_COMPLETION_DRAIN_FAILURE_CODES = new Set<string>(
  F005_WRITE_COMPLETION_DRAIN_FAILURE_STAGES.map(
    (stage) => `F005_ETW_WRITE_COMPLETION_DRAIN_${stage}`,
  ),
);
const F005_NATIVE_SYSTEM_BOUND_FILE_OBJECT_REJOIN_DIAGNOSTIC = new RegExp(
  '^ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_BOUND_FILE_OBJECT_REJOIN_' +
  '(?:SNAPSHOT_MISSING|PATH_MISMATCH|CURRENT_MISSING|IDENTITY_MISMATCH|' +
  'LEASE_(?:MISSING|PHASE|BINDING|CLOSED|ESCAPE)|' +
  'NO_PENDING_(?:FILE|OTHER|CANDIDATE|STATE_DRIFT|' +
  'DIR_(?:SNAPSHOT_MISSING|CURRENT_MISSING|ID_MISMATCH|OWNER_MISSING|' +
  'ROOT_INACTIVE|UNKNOWN)|LEASE_(?:PARENT|CLOSED|' +
  'SNAPSHOT_MISSING|BINDING_(?:MISSING|MISMATCH)|CURRENT_MISSING|' +
  'ID_MISMATCH|ESCAPE)|UNBOUND_(?:SNAPSHOT_PRESENT|BEFORE_RESERVATION|' +
  'CURRENT_(?:INSPECTION_FAILED|MISSING|ID_MISMATCH)|' +
  'DEFERRED_(?:MISSING|TUPLE)|PROCESS_(?:WAIT_FAILED|IDENTITY_FAILED|' +
  'TUPLE|SIGNALED)|JOB_QUERY_FAILED|LEASE_ESCAPE|CANDIDATE))|CANDIDATE)$',
  'u',
);
const F005_NATIVE_SYSTEM_BOUND_FILE_OBJECT_RENAME_LEASE_PATH_REJOIN_DIAGNOSTIC =
  new RegExp(
    '^ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_BOUND_FILE_OBJECT_REJOIN_' +
    'RENAME_LEASE_PATH_(?:TARGET_MISMATCH|' +
    'RESERVATION_(?:MISSING|ORDER)|BEFORE_LEASE_RESERVATION|' +
    'AFTER_LEASE_RESERVATION|LEASE_CURRENT_EXISTS|SNAPSHOT_(?:MISSING|PATH)|' +
    'IDENTITY_MISMATCH|BINDING_MISMATCH|LEASE_(?:CLOSED|ESCAPE)|CANDIDATE)$',
  'u',
);

export function isF005SystemSetInfoDiagnosticCode(
  value: unknown,
): value is F005SystemSetInfoDiagnosticCode {
  return typeof value === 'string' &&
    value.length <= 127 &&
    value.startsWith('F005_') &&
    F005_NATIVE_SYSTEM_SETINFO_DIAGNOSTIC.test(value.slice(5));
}

export function isF005SystemSetInfoCorrelationDiagnosticCode(
  value: unknown,
): value is F005SystemSetInfoCorrelationDiagnosticCode {
  return typeof value === 'string' &&
    value.length <= 127 &&
    value.startsWith('F005_') &&
    F005_NATIVE_SYSTEM_SETINFO_CORRELATION_DIAGNOSTIC.test(value.slice(5));
}

export function isF005CompletedWriteRejoinDiagnosticCode(
  value: unknown,
): value is F005CompletedWriteRejoinDiagnosticCode {
  return typeof value === 'string' &&
    value.length <= 96 &&
    value.startsWith('F005_') &&
    F005_NATIVE_COMPLETED_WRITE_REJOIN_DIAGNOSTIC.test(value.slice(5));
}

export function isF005ClosedLeaseRejoinDiagnosticCode(
  value: unknown,
): value is F005ClosedLeaseRejoinDiagnosticCode {
  return typeof value === 'string' &&
    value.length <= 96 &&
    value.startsWith('F005_') &&
    F005_NATIVE_CLOSED_LEASE_REJOIN_DIAGNOSTIC.test(value.slice(5));
}

export function isF005SystemUnboundWriteDiagnosticCode(
  value: unknown,
): value is F005SystemUnboundWriteDiagnosticCode {
  return typeof value === 'string' &&
    value.length <= 127 &&
    value.startsWith('F005_') &&
    F005_NATIVE_SYSTEM_UNBOUND_WRITE_DIAGNOSTIC.test(value.slice(5));
}

export function isF005SystemUnboundWriteOtherKnownPathDiagnosticCode(
  value: unknown,
): value is F005SystemUnboundWriteOtherKnownPathDiagnosticCode {
  return typeof value === 'string' &&
    value.length <= 127 &&
    value.startsWith('F005_') &&
    F005_NATIVE_SYSTEM_UNBOUND_WRITE_OTHER_KNOWN_PATH_DIAGNOSTIC.test(
      value.slice(5),
    );
}

export function isF005SystemDirectoryWriteRejoinDiagnosticCode(
  value: unknown,
): value is F005SystemDirectoryWriteRejoinDiagnosticCode {
  return typeof value === 'string' &&
    value.length <= 96 &&
    value.startsWith('F005_') &&
    F005_NATIVE_SYSTEM_DIRECTORY_WRITE_REJOIN_DIAGNOSTIC.test(value.slice(5));
}

export function isF005SystemDirectoryActiveLeaseWriteRejoinDiagnosticCode(
  value: unknown,
): value is F005SystemDirectoryActiveLeaseWriteRejoinDiagnosticCode {
  return typeof value === 'string' &&
    value.length <= 127 &&
    value.startsWith('F005_') &&
    F005_NATIVE_SYSTEM_DIRECTORY_ACTIVE_LEASE_WRITE_REJOIN_DIAGNOSTIC.test(
      value.slice(5),
    );
}

export function isF005SystemDirectoryBoundLeaseWriteRejoinDiagnosticCode(
  value: unknown,
): value is F005SystemDirectoryBoundLeaseWriteRejoinDiagnosticCode {
  return typeof value === 'string' &&
    value.length <= 127 &&
    value.startsWith('F005_') &&
    F005_NATIVE_SYSTEM_DIRECTORY_BOUND_LEASE_WRITE_REJOIN_DIAGNOSTIC.test(
      value.slice(5),
    );
}

export function isF005SystemDirectoryBoundLeaseRenameWriteRejoinDiagnosticCode(
  value: unknown,
): value is F005SystemDirectoryBoundLeaseRenameWriteRejoinDiagnosticCode {
  return typeof value === 'string' &&
    value.length <= 127 &&
    value.startsWith('F005_') &&
    F005_NATIVE_SYSTEM_DIRECTORY_BOUND_LEASE_RENAME_WRITE_REJOIN_DIAGNOSTIC
      .test(value.slice(5));
}

export function isF005AfterLeaseReservationDirectoryRejoinFailureCode(
  value: unknown,
): value is F005AfterLeaseReservationDirectoryRejoinFailureCode {
  return typeof value === 'string' &&
    value.length <= 127 &&
    value.startsWith('F005_') &&
    F005_NATIVE_AFTER_LEASE_RESERVATION_DIRECTORY_REJOIN_FAILURE.test(
      value.slice(5),
    );
}

export function isF005SystemDirectoryBoundLeaseRejoinFailureCode(
  value: unknown,
): value is F005SystemDirectoryBoundLeaseRejoinFailureCode {
  return typeof value === 'string' &&
    value.length <= 127 &&
    value.startsWith('F005_') &&
    F005_NATIVE_SYSTEM_DIRECTORY_BOUND_LEASE_REJOIN_FAILURE.test(
      value.slice(5),
    );
}

export function isF005WriteCompletionDrainFailureCode(
  value: unknown,
): value is F005WriteCompletionDrainFailureCode {
  return typeof value === 'string' &&
    value.length <= 127 &&
    F005_WRITE_COMPLETION_DRAIN_FAILURE_CODES.has(value);
}

export function isF005SystemBoundFileObjectRejoinDiagnosticCode(
  value: unknown,
): value is F005SystemBoundFileObjectRejoinDiagnosticCode {
  return typeof value === 'string' &&
    value.length <= 127 &&
    value.startsWith('F005_') &&
    F005_NATIVE_SYSTEM_BOUND_FILE_OBJECT_REJOIN_DIAGNOSTIC.test(
      value.slice(5),
    );
}

export function isF005SystemBoundFileObjectRenameLeasePathRejoinDiagnosticCode(
  value: unknown,
): value is F005SystemBoundFileObjectRenameLeasePathRejoinDiagnosticCode {
  return typeof value === 'string' &&
    value.length <= 127 &&
    value.startsWith('F005_') &&
    F005_NATIVE_SYSTEM_BOUND_FILE_OBJECT_RENAME_LEASE_PATH_REJOIN_DIAGNOSTIC
      .test(value.slice(5));
}

export type F005NativeCapacityErrorCode =
  | F005SystemSetInfoDiagnosticCode
  | F005SystemSetInfoCorrelationDiagnosticCode
  | F005CompletedWriteRejoinDiagnosticCode
  | F005ClosedLeaseRejoinDiagnosticCode
  | F005SystemUnboundWriteDiagnosticCode
  | F005SystemUnboundWriteOtherKnownPathDiagnosticCode
  | F005SystemDirectoryWriteRejoinDiagnosticCode
  | F005SystemDirectoryActiveLeaseWriteRejoinDiagnosticCode
  | F005SystemDirectoryBoundLeaseWriteRejoinDiagnosticCode
  | F005SystemDirectoryBoundLeaseRenameWriteRejoinDiagnosticCode
  | F005AfterLeaseReservationDirectoryRejoinFailureCode
  | F005SystemDirectoryBoundLeaseRejoinFailureCode
  | F005WriteCompletionDrainFailureCode
  | F005WriteLeaseProducerBirthFailureCode
  | F005SystemBoundFileObjectRejoinDiagnosticCode
  | F005SystemBoundFileObjectRenameLeasePathRejoinDiagnosticCode
  | 'F005_NATIVE_GUARD_INVALID'
  | 'F005_NATIVE_GUARD_CHANNEL_FAILED'
  | 'F005_NATIVE_WRITE_THROUGH_OPEN_FAILED'
  | 'F005_NATIVE_WRITE_THROUGH_FLUSH_FAILED'
  | 'F005_NATIVE_WRITE_THROUGH_IDENTITY_FAILED'
  | 'F005_NATIVE_WRITE_THROUGH_VERIFY_FAILED'
  | 'F005_NATIVE_WRITE_THROUGH_CLEANUP_FAILED'
  | 'F005_NATIVE_WRITE_THROUGH_PROTOCOL_FAILED'
  | 'F005_ETW_PRIVILEGE_REQUIRED'
  | 'F005_CAPACITY_IPC_FAILED'
  | 'F005_CAPACITY_IPC_CONNECT_FAILED'
  | 'F005_CAPACITY_REGISTER_SELF_FAILED'
  | 'F005_CAPACITY_PROCESS_IDENTITY_PROBE_ARM_FAILED'
  | 'F005_CAPACITY_PROCESS_IDENTITY_PROBE_WRITE_FAILED'
  | 'F005_CAPACITY_PROCESS_IDENTITY_PROBE_VERIFY_FAILED'
  | 'F005_CAPACITY_GUARD_REJECTED'
  | 'F005_CAPACITY_ETW_OBSERVATION_FAILED'
  | 'F005_CAPACITY_NOTICE_UNMATCHED'
  | 'F005_ETW_ALLOCATED_LENGTH_MISSING'
  | 'F005_ETW_BUFFER_LOSS'
  | 'F005_ETW_CALLBACK_FAILED'
  | 'F005_ETW_CALLBACK_ACCESS_FAILED'
  | 'F005_ETW_CALLBACK_ARGUMENT_FAILED'
  | 'F005_ETW_CALLBACK_AUTHORIZATION_FAILED'
  | 'F005_ETW_CALLBACK_CAPACITY_FAILED'
  | 'F005_ETW_CALLBACK_CORRELATION_FAILED'
  | 'F005_ETW_CALLBACK_DISPOSED'
  | 'F005_ETW_CALLBACK_IDENTITY_FAILED'
  | 'F005_ETW_CALLBACK_IO_FAILED'
  | 'F005_ETW_CALLBACK_JOURNAL_FAILED'
  | 'F005_ETW_CALLBACK_LOCK_STATE_FAILED'
  | 'F005_ETW_CALLBACK_NORMALIZE_FAILED'
  | 'F005_ETW_CALLBACK_OVERFLOW'
  | 'F005_ETW_CALLBACK_PHASE_FAILED'
  | 'F005_ETW_CALLBACK_RECORD_FAILED'
  | 'F005_ETW_CALLBACK_STATE_FAILED'
  | 'F005_ETW_CONSUMER_FAILED'
  | 'F005_ETW_CONSUMER_DRAIN_FAILED'
  | 'F005_ETW_CONSUMER_DRAIN_TIMEOUT'
  | 'F005_ETW_CONSUMER_STOP_TIMEOUT'
  | 'F005_ETW_EVENT_OUTSIDE_PHASE'
  | 'F005_ETW_EVENT_PHASE_TIMESTAMP_MISMATCH'
  | 'F005_ETW_FILE_IDENTITY_MISSING'
  | 'F005_ETW_FILE_IDENTITY_MISSING_CREATE_CORRELATION'
  | 'F005_ETW_FILE_IDENTITY_MISSING_CREATE_IDENTITY'
  | 'F005_ETW_FILE_IDENTITY_MISSING_DELETE_CORRELATION'
  | 'F005_ETW_FILE_IDENTITY_MISSING_DELETE_IDENTITY'
  | 'F005_ETW_FILE_IDENTITY_MISSING_RENAME_CORRELATION'
  | 'F005_ETW_FILE_IDENTITY_MISSING_RENAME_IDENTITY'
  | 'F005_ETW_FILE_IDENTITY_MISSING_SETINFO_CORRELATION'
  | 'F005_ETW_FILE_IDENTITY_MISSING_SETINFO_IDENTITY'
  | 'F005_ETW_FILE_IDENTITY_MISSING_WRITE_CORRELATION'
  | 'F005_ETW_FILE_IDENTITY_MISSING_WRITE_IDENTITY'
  | 'F005_ETW_FILE_IDENTITY_UNSAFE'
  | 'F005_ETW_OBSERVATION_MISSING'
  | 'F005_ETW_PID_NOT_JOB_MEMBER'
  | 'F005_ETW_PID_NOT_JOB_MEMBER_BIRTH_MISSING'
  | 'F005_ETW_PID_NOT_JOB_MEMBER_BIRTH_MISSING_BOUND_FILE_OBJECT'
  | 'F005_ETW_PID_NOT_JOB_MEMBER_EVENT_BEFORE_BIRTH'
  | 'F005_ETW_PID_NOT_JOB_MEMBER_EVENT_KEY_MISMATCH'
  | 'F005_ETW_PID_NOT_JOB_MEMBER_PROCESS_IDENTITY_UNAVAILABLE'
  | 'F005_ETW_PID_NOT_JOB_MEMBER_PROCESS_UNAVAILABLE'
  | 'F005_ETW_PID_NOT_JOB_MEMBER_RETAINED_OUTSIDE_JOB'
  | 'F005_ETW_PID_NOT_JOB_MEMBER_ROOT_INACTIVE'
  | 'F005_ETW_PID_NOT_JOB_MEMBER_SEQUENCE_MISMATCH'
  | 'F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT'
  | 'F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_CREATE_KNOWN_PATH'
  | 'F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_CREATE_UNKNOWN_PATH'
  | 'F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_DELETE_KNOWN_PATH'
  | 'F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_DELETE_UNKNOWN_PATH'
  | 'F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_RENAME_KNOWN_PATH'
  | 'F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_RENAME_UNKNOWN_PATH'
  | 'F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_SETINFO_KNOWN_PATH'
  | 'F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_SETINFO_UNKNOWN_PATH'
  | 'F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_WRITE_KNOWN_PATH'
  | 'F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_WRITE_UNKNOWN_PATH'
  | 'F005_ETW_PROCESS_START_KEY_MISSING'
  | 'F005_ETW_PROCESS_START_KEY_PROBE_FAILED'
  | 'F005_ETW_PROCESS_START_KEY_PROBE_IDENTITY_MISMATCH'
  | 'F005_ETW_PROCESS_START_KEY_PROBE_REQUIRED'
  | 'F005_ETW_PROCESS_START_KEY_PROBE_TIMEOUT'
  | 'F005_ETW_RENAME_IDENTITY_MISMATCH'
  | 'F005_ETW_SEQUENCE_GAP'
  | 'F005_ETW_SYSTEM_SETINFO_CORRELATION_MISMATCH'
  | 'F005_ETW_SYSTEM_DIRECTORY_WRITE_REJOIN_IDENTITY_MISMATCH'
  | 'F005_ETW_SESSION_STOP_FAILED'
  | 'F005_ETW_UNKNOWN_EVENT'
  | 'F005_CAPACITY_JOURNAL_INVALID'
  | 'F005_DIRECTORY_SYNC_FAILED';

export class F005NativeCapacityError extends Error {
  constructor(
    readonly code: F005NativeCapacityErrorCode,
    message: string,
    options?: ErrorOptions,
  ) {
    super(message, options);
    this.name = 'F005NativeCapacityError';
  }
}

function fail(
  code: F005NativeCapacityErrorCode,
  message: string,
  cause?: unknown,
): never {
  throw new F005NativeCapacityError(
    code,
    message,
    cause === undefined ? undefined : { cause },
  );
}

export function preserveF005NativeCapacityFailure(
  error: unknown,
  message: string,
): never {
  if (error instanceof F005NativeCapacityError) throw error;
  return fail('F005_CAPACITY_IPC_FAILED', message, error);
}

const FIXED_F005_ETW_REPLY_CODES: ReadonlyMap<string, F005NativeCapacityErrorCode> = new Map([
  ['WRITE_LEASE_PRODUCER_BIRTH_TIMEOUT', 'F005_WRITE_LEASE_PRODUCER_BIRTH_TIMEOUT'],
  ['WRITE_LEASE_PRODUCER_BIRTH_TUPLE_MISMATCH', 'F005_WRITE_LEASE_PRODUCER_BIRTH_TUPLE_MISMATCH'],
  ['WRITE_LEASE_PRODUCER_BIRTH_PROCESS_IDENTITY_FAILED', 'F005_WRITE_LEASE_PRODUCER_BIRTH_PROCESS_IDENTITY_FAILED'],
  ['WRITE_LEASE_PRODUCER_BIRTH_STATE_CHANGED', 'F005_WRITE_LEASE_PRODUCER_BIRTH_STATE_CHANGED'],
  ['ETW_ALLOCATED_LENGTH_MISSING', 'F005_ETW_ALLOCATED_LENGTH_MISSING'],
  ['ETW_BUFFER_LOSS', 'F005_ETW_BUFFER_LOSS'],
  ['ETW_CALLBACK_ACCESS_FAILED', 'F005_ETW_CALLBACK_ACCESS_FAILED'],
  ['ETW_CALLBACK_ARGUMENT_FAILED', 'F005_ETW_CALLBACK_ARGUMENT_FAILED'],
  ['ETW_CALLBACK_AUTHORIZATION_FAILED', 'F005_ETW_CALLBACK_AUTHORIZATION_FAILED'],
  ['ETW_CALLBACK_CAPACITY_FAILED', 'F005_ETW_CALLBACK_CAPACITY_FAILED'],
  ['ETW_CALLBACK_CORRELATION_FAILED', 'F005_ETW_CALLBACK_CORRELATION_FAILED'],
  ['ETW_CALLBACK_DISPOSED', 'F005_ETW_CALLBACK_DISPOSED'],
  ['ETW_CALLBACK_IDENTITY_FAILED', 'F005_ETW_CALLBACK_IDENTITY_FAILED'],
  ['ETW_CALLBACK_FAILED', 'F005_ETW_CALLBACK_FAILED'],
  ['ETW_CALLBACK_IO_FAILED', 'F005_ETW_CALLBACK_IO_FAILED'],
  ['ETW_CALLBACK_JOURNAL_FAILED', 'F005_ETW_CALLBACK_JOURNAL_FAILED'],
  ['ETW_CALLBACK_LOCK_STATE_FAILED', 'F005_ETW_CALLBACK_LOCK_STATE_FAILED'],
  ['ETW_CALLBACK_NORMALIZE_FAILED', 'F005_ETW_CALLBACK_NORMALIZE_FAILED'],
  ['ETW_CALLBACK_OVERFLOW', 'F005_ETW_CALLBACK_OVERFLOW'],
  ['ETW_CALLBACK_PHASE_FAILED', 'F005_ETW_CALLBACK_PHASE_FAILED'],
  ['ETW_CALLBACK_RECORD_FAILED', 'F005_ETW_CALLBACK_RECORD_FAILED'],
  ['ETW_CALLBACK_STATE_FAILED', 'F005_ETW_CALLBACK_STATE_FAILED'],
  ['ETW_CONSUMER_DRAIN_FAILED', 'F005_ETW_CONSUMER_DRAIN_FAILED'],
  ['ETW_CONSUMER_DRAIN_TIMEOUT', 'F005_ETW_CONSUMER_DRAIN_TIMEOUT'],
  ['ETW_CONSUMER_STOP_TIMEOUT', 'F005_ETW_CONSUMER_STOP_TIMEOUT'],
  ['ETW_EVENT_OUTSIDE_PHASE', 'F005_ETW_EVENT_OUTSIDE_PHASE'],
  ['ETW_EVENT_PHASE_TIMESTAMP_MISMATCH', 'F005_ETW_EVENT_PHASE_TIMESTAMP_MISMATCH'],
  ['ETW_FILE_IDENTITY_MISSING', 'F005_ETW_FILE_IDENTITY_MISSING'],
  ['ETW_FILE_IDENTITY_MISSING_CREATE_CORRELATION', 'F005_ETW_FILE_IDENTITY_MISSING_CREATE_CORRELATION'],
  ['ETW_FILE_IDENTITY_MISSING_CREATE_IDENTITY', 'F005_ETW_FILE_IDENTITY_MISSING_CREATE_IDENTITY'],
  ['ETW_FILE_IDENTITY_MISSING_DELETE_CORRELATION', 'F005_ETW_FILE_IDENTITY_MISSING_DELETE_CORRELATION'],
  ['ETW_FILE_IDENTITY_MISSING_DELETE_IDENTITY', 'F005_ETW_FILE_IDENTITY_MISSING_DELETE_IDENTITY'],
  ['ETW_FILE_IDENTITY_MISSING_RENAME_CORRELATION', 'F005_ETW_FILE_IDENTITY_MISSING_RENAME_CORRELATION'],
  ['ETW_FILE_IDENTITY_MISSING_RENAME_IDENTITY', 'F005_ETW_FILE_IDENTITY_MISSING_RENAME_IDENTITY'],
  ['ETW_FILE_IDENTITY_MISSING_SETINFO_CORRELATION', 'F005_ETW_FILE_IDENTITY_MISSING_SETINFO_CORRELATION'],
  ['ETW_FILE_IDENTITY_MISSING_SETINFO_IDENTITY', 'F005_ETW_FILE_IDENTITY_MISSING_SETINFO_IDENTITY'],
  ['ETW_FILE_IDENTITY_MISSING_WRITE_CORRELATION', 'F005_ETW_FILE_IDENTITY_MISSING_WRITE_CORRELATION'],
  ['ETW_FILE_IDENTITY_MISSING_WRITE_IDENTITY', 'F005_ETW_FILE_IDENTITY_MISSING_WRITE_IDENTITY'],
  ['ETW_FILE_IDENTITY_UNSAFE', 'F005_ETW_FILE_IDENTITY_UNSAFE'],
  ['ETW_OBSERVATION_MISSING', 'F005_ETW_OBSERVATION_MISSING'],
  ['ETW_PID_NOT_JOB_MEMBER', 'F005_ETW_PID_NOT_JOB_MEMBER'],
  ['ETW_PID_NOT_JOB_MEMBER_BIRTH_MISSING', 'F005_ETW_PID_NOT_JOB_MEMBER_BIRTH_MISSING'],
  ['ETW_PID_NOT_JOB_MEMBER_BIRTH_MISSING_BOUND_FILE_OBJECT', 'F005_ETW_PID_NOT_JOB_MEMBER_BIRTH_MISSING_BOUND_FILE_OBJECT'],
  ['ETW_PID_NOT_JOB_MEMBER_EVENT_BEFORE_BIRTH', 'F005_ETW_PID_NOT_JOB_MEMBER_EVENT_BEFORE_BIRTH'],
  ['ETW_PID_NOT_JOB_MEMBER_EVENT_KEY_MISMATCH', 'F005_ETW_PID_NOT_JOB_MEMBER_EVENT_KEY_MISMATCH'],
  ['ETW_PID_NOT_JOB_MEMBER_PROCESS_IDENTITY_UNAVAILABLE', 'F005_ETW_PID_NOT_JOB_MEMBER_PROCESS_IDENTITY_UNAVAILABLE'],
  ['ETW_PID_NOT_JOB_MEMBER_PROCESS_UNAVAILABLE', 'F005_ETW_PID_NOT_JOB_MEMBER_PROCESS_UNAVAILABLE'],
  ['ETW_PID_NOT_JOB_MEMBER_RETAINED_OUTSIDE_JOB', 'F005_ETW_PID_NOT_JOB_MEMBER_RETAINED_OUTSIDE_JOB'],
  ['ETW_PID_NOT_JOB_MEMBER_ROOT_INACTIVE', 'F005_ETW_PID_NOT_JOB_MEMBER_ROOT_INACTIVE'],
  ['ETW_PID_NOT_JOB_MEMBER_SEQUENCE_MISMATCH', 'F005_ETW_PID_NOT_JOB_MEMBER_SEQUENCE_MISMATCH'],
  ['ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT', 'F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT'],
  ['ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_CREATE_KNOWN_PATH', 'F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_CREATE_KNOWN_PATH'],
  ['ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_CREATE_UNKNOWN_PATH', 'F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_CREATE_UNKNOWN_PATH'],
  ['ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_DELETE_KNOWN_PATH', 'F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_DELETE_KNOWN_PATH'],
  ['ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_DELETE_UNKNOWN_PATH', 'F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_DELETE_UNKNOWN_PATH'],
  ['ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_RENAME_KNOWN_PATH', 'F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_RENAME_KNOWN_PATH'],
  ['ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_RENAME_UNKNOWN_PATH', 'F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_RENAME_UNKNOWN_PATH'],
  ['ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_SETINFO_KNOWN_PATH', 'F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_SETINFO_KNOWN_PATH'],
  ['ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_SETINFO_UNKNOWN_PATH', 'F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_SETINFO_UNKNOWN_PATH'],
  ['ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_WRITE_KNOWN_PATH', 'F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_WRITE_KNOWN_PATH'],
  ['ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_WRITE_UNKNOWN_PATH', 'F005_ETW_PID_NOT_JOB_MEMBER_SYSTEM_PROCESS_UNBOUND_FILE_OBJECT_WRITE_UNKNOWN_PATH'],
  ['ETW_PROCESS_START_KEY_MISSING', 'F005_ETW_PROCESS_START_KEY_MISSING'],
  ['ETW_PROCESS_START_KEY_PROBE_FAILED', 'F005_ETW_PROCESS_START_KEY_PROBE_FAILED'],
  ['ETW_PROCESS_START_KEY_PROBE_IDENTITY_MISMATCH', 'F005_ETW_PROCESS_START_KEY_PROBE_IDENTITY_MISMATCH'],
  ['ETW_PROCESS_START_KEY_PROBE_REQUIRED', 'F005_ETW_PROCESS_START_KEY_PROBE_REQUIRED'],
  ['ETW_PROCESS_START_KEY_PROBE_TIMEOUT', 'F005_ETW_PROCESS_START_KEY_PROBE_TIMEOUT'],
  ['ETW_RENAME_IDENTITY_MISMATCH', 'F005_ETW_RENAME_IDENTITY_MISMATCH'],
  ['ETW_SEQUENCE_GAP', 'F005_ETW_SEQUENCE_GAP'],
  ['ETW_SYSTEM_SETINFO_CORRELATION_MISMATCH', 'F005_ETW_SYSTEM_SETINFO_CORRELATION_MISMATCH'],
  ['ETW_SYSTEM_DIRECTORY_WRITE_REJOIN_IDENTITY_MISMATCH', 'F005_ETW_SYSTEM_DIRECTORY_WRITE_REJOIN_IDENTITY_MISMATCH'],
  ['ETW_UNKNOWN_EVENT', 'F005_ETW_UNKNOWN_EVENT'],
]);

export function classifyF005NativeCapacityReplyError(value: unknown): F005NativeCapacityErrorCode {
  if (value === 'F005_CAPACITY_NOTICE_UNMATCHED') return 'F005_CAPACITY_NOTICE_UNMATCHED';
  if (isF005WriteCompletionDrainFailureCode(value)) return value;
  if (isF005WriteLeaseProducerBirthFailureCode(value)) return value;
  if (typeof value === 'string' && value.startsWith('ETW_PRIVILEGE_REQUIRED')) {
    return 'F005_ETW_PRIVILEGE_REQUIRED';
  }
  const fixedCode = typeof value === 'string'
    ? FIXED_F005_ETW_REPLY_CODES.get(value)
    : undefined;
  if (fixedCode !== undefined) return fixedCode;
  if (typeof value === 'string' && F005_NATIVE_SYSTEM_SETINFO_DIAGNOSTIC.test(value)) {
    return `F005_${value}` as F005SystemSetInfoDiagnosticCode;
  }
  if (typeof value === 'string' &&
    F005_NATIVE_SYSTEM_SETINFO_CORRELATION_DIAGNOSTIC.test(value)) {
    return `F005_${value}` as F005SystemSetInfoCorrelationDiagnosticCode;
  }
  if (typeof value === 'string' &&
    F005_NATIVE_COMPLETED_WRITE_REJOIN_DIAGNOSTIC.test(value)) {
    return `F005_${value}` as F005CompletedWriteRejoinDiagnosticCode;
  }
  if (typeof value === 'string' &&
    F005_NATIVE_CLOSED_LEASE_REJOIN_DIAGNOSTIC.test(value)) {
    return `F005_${value}` as F005ClosedLeaseRejoinDiagnosticCode;
  }
  if (typeof value === 'string' &&
    F005_NATIVE_SYSTEM_UNBOUND_WRITE_DIAGNOSTIC.test(value)) {
    return `F005_${value}` as F005SystemUnboundWriteDiagnosticCode;
  }
  if (typeof value === 'string' &&
    F005_NATIVE_SYSTEM_UNBOUND_WRITE_OTHER_KNOWN_PATH_DIAGNOSTIC.test(value)) {
    return `F005_${value}` as F005SystemUnboundWriteOtherKnownPathDiagnosticCode;
  }
  if (typeof value === 'string' &&
    F005_NATIVE_SYSTEM_DIRECTORY_WRITE_REJOIN_DIAGNOSTIC.test(value)) {
    return `F005_${value}` as F005SystemDirectoryWriteRejoinDiagnosticCode;
  }
  if (typeof value === 'string' &&
    F005_NATIVE_SYSTEM_DIRECTORY_ACTIVE_LEASE_WRITE_REJOIN_DIAGNOSTIC.test(value)) {
    return `F005_${value}` as F005SystemDirectoryActiveLeaseWriteRejoinDiagnosticCode;
  }
  if (typeof value === 'string' &&
    F005_NATIVE_SYSTEM_DIRECTORY_BOUND_LEASE_WRITE_REJOIN_DIAGNOSTIC.test(value)) {
    return `F005_${value}` as F005SystemDirectoryBoundLeaseWriteRejoinDiagnosticCode;
  }
  if (typeof value === 'string' &&
    F005_NATIVE_SYSTEM_DIRECTORY_BOUND_LEASE_RENAME_WRITE_REJOIN_DIAGNOSTIC
      .test(value)) {
    return `F005_${value}` as F005SystemDirectoryBoundLeaseRenameWriteRejoinDiagnosticCode;
  }
  if (typeof value === 'string' &&
    F005_NATIVE_AFTER_LEASE_RESERVATION_DIRECTORY_REJOIN_FAILURE.test(value)) {
    return `F005_${value}` as F005AfterLeaseReservationDirectoryRejoinFailureCode;
  }
  if (typeof value === 'string' &&
    F005_NATIVE_SYSTEM_DIRECTORY_BOUND_LEASE_REJOIN_FAILURE.test(value)) {
    return `F005_${value}` as F005SystemDirectoryBoundLeaseRejoinFailureCode;
  }
  if (typeof value === 'string' &&
    F005_NATIVE_SYSTEM_BOUND_FILE_OBJECT_RENAME_LEASE_PATH_REJOIN_DIAGNOSTIC
      .test(value)) {
    return `F005_${value}` as F005SystemBoundFileObjectRenameLeasePathRejoinDiagnosticCode;
  }
  if (typeof value === 'string' &&
    F005_NATIVE_SYSTEM_BOUND_FILE_OBJECT_REJOIN_DIAGNOSTIC.test(value)) {
    return `F005_${value}` as F005SystemBoundFileObjectRejoinDiagnosticCode;
  }
  if (typeof value === 'string' && value.startsWith('ETW_CONSUMER_FAILED_')) {
    return 'F005_ETW_CONSUMER_FAILED';
  }
  if (typeof value === 'string' && value.startsWith('ETW_OBSERVATION_FAILED_')) {
    return 'F005_ETW_CALLBACK_FAILED';
  }
  if (typeof value === 'string' && value.startsWith('ETW_SESSION_STOP_FAILED_')) {
    return 'F005_ETW_SESSION_STOP_FAILED';
  }
  if (typeof value === 'string' && value.startsWith('ETW_')) {
    return 'F005_CAPACITY_ETW_OBSERVATION_FAILED';
  }
  return 'F005_CAPACITY_GUARD_REJECTED';
}

export function classifyF005NativeWriteThroughReplyError(
  value: unknown,
): F005NativeCapacityErrorCode {
  if (typeof value !== 'string') return 'F005_NATIVE_WRITE_THROUGH_PROTOCOL_FAILED';
  if (
    value.startsWith('WRITE_THROUGH_OPEN_FAILED_')
    || value.startsWith('DIRECTORY_OPEN_FAILED_')
  ) {
    return 'F005_NATIVE_WRITE_THROUGH_OPEN_FAILED';
  }
  if (value.startsWith('WRITE_THROUGH_FLUSH_FAILED_')) {
    return 'F005_NATIVE_WRITE_THROUGH_FLUSH_FAILED';
  }
  if (
    value === 'WRITE_THROUGH_IDENTITY_UNSAFE'
    || value.startsWith('DIRECTORY_IDENTITY_FAILED_')
    || value.startsWith('DIRECTORY_FINAL_PATH_FAILED_')
    || value.startsWith('IDENTITY_READ_FAILED_')
  ) {
    return 'F005_NATIVE_WRITE_THROUGH_IDENTITY_FAILED';
  }
  if (
    value === 'WRITE_THROUGH_LENGTH_MISMATCH'
    || value === 'WRITE_THROUGH_PARTIAL_READ'
    || value === 'WRITE_THROUGH_READBACK_MISMATCH'
    || value === 'WRITE_THROUGH_HASH_MISMATCH'
  ) {
    return 'F005_NATIVE_WRITE_THROUGH_VERIFY_FAILED';
  }
  if (
    value === 'WRITE_THROUGH_CLEANUP_FAILED'
    || value.startsWith('WRITE_THROUGH_DELETE_ON_CLOSE_CLEAR_FAILED_')
  ) {
    return 'F005_NATIVE_WRITE_THROUGH_CLEANUP_FAILED';
  }
  return 'F005_NATIVE_WRITE_THROUGH_PROTOCOL_FAILED';
}

function sha256(value: string | Uint8Array): string {
  return createHash('sha256').update(value).digest('hex');
}

function record(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value) &&
    (Object.getPrototypeOf(value) === Object.prototype || Object.getPrototypeOf(value) === null);
}

function exactKeys(value: Record<string, unknown>, expected: readonly string[]): boolean {
  const actual = Object.keys(value).sort((left, right) => left.localeCompare(right, 'en'));
  const sortedExpected = [...expected].sort((left, right) => left.localeCompare(right, 'en'));
  return actual.length === sortedExpected.length &&
    actual.every((key, index) => key === sortedExpected[index]);
}

function safeInteger(value: unknown): value is number {
  return Number.isSafeInteger(value) && Number(value) >= 0;
}

function safeString(value: unknown): value is string {
  return typeof value === 'string' && value.trim() === value && value.length > 0;
}

function safeRelativePath(value: unknown): value is string {
  return typeof value === 'string' && SAFE_PATH.test(value) &&
    !value.split('/').some((segment) =>
      segment === '' || segment === '.' || segment === '..' ||
      segment.endsWith('.') || segment.endsWith(' ') ||
      segment.normalize('NFC') !== segment);
}

/**
 * application層の絶対pathをnative journal ABIのworkspace相対pathへ変換する。
 * workspace外・workspace自体・非正規pathはfail-closedとする。
 */
export function normalizeF005CapacityNoticePath(workspace: string, value: unknown): string {
  if (!isAbsolute(workspace) || resolve(workspace) !== workspace || typeof value !== 'string') {
    return fail('F005_CAPACITY_IPC_FAILED', 'mutation notice pathが不正です');
  }
  const target = isAbsolute(value) ? resolve(value) : resolve(workspace, value);
  const normalized = relative(workspace, target).split(sep).join('/');
  if (!normalized || normalized === '..' || normalized.startsWith('../') ||
    isAbsolute(normalized) || !safeRelativePath(normalized)) {
    return fail('F005_CAPACITY_IPC_FAILED', 'mutation notice pathがworkspace外です');
  }
  return normalized;
}

/**
 * WindowsでNodeから開けないdirectory write handleを固定native guardで開き、
 * accepted manifest参照artifactのrenameをFlushFileBuffersで永続化する。
 * @des DES-F005-006 @fun FUN-F005-022 @ut UT-F005-022
 */
export async function flushF005ArtifactDirectory(
  workspace: string,
  directory: string,
  options: { readonly executable?: string } = {},
): Promise<void> {
  if (!isAbsolute(workspace) || resolve(workspace) !== workspace ||
    !isAbsolute(directory) || resolve(directory) !== directory) {
    return fail('F005_DIRECTORY_SYNC_FAILED', 'directory sync pathが非canonicalです');
  }
  const relativeDirectory = relative(workspace, directory).split(sep).join('/');
  if (!relativeDirectory || relativeDirectory === '..' ||
    relativeDirectory.startsWith('../') || isAbsolute(relativeDirectory) ||
    !safeRelativePath(relativeDirectory)) {
    return fail('F005_DIRECTORY_SYNC_FAILED', 'directory sync pathがworkspace外です');
  }
  const [workspaceInfo, directoryInfo, workspaceReal, directoryReal] = await Promise.all([
    lstat(workspace),
    lstat(directory),
    realpath(workspace),
    realpath(directory),
  ]).catch((error) =>
    fail('F005_DIRECTORY_SYNC_FAILED', 'directory sync対象を検証できません', error));
  if (!workspaceInfo.isDirectory() || workspaceInfo.isSymbolicLink() ||
    !directoryInfo.isDirectory() || directoryInfo.isSymbolicLink() ||
    workspaceReal !== workspace || directoryReal !== directory) {
    return fail('F005_DIRECTORY_SYNC_FAILED', 'directory sync対象の実体が不正です');
  }

  const executable = options.executable ??
    await resolveF005NativeGuardExecutable(workspace);
  if (!isAbsolute(executable) || resolve(executable) !== executable) {
    return fail('F005_NATIVE_GUARD_INVALID', 'native guard pathが非canonicalです');
  }
  const binary = await readFile(executable).catch((error) =>
    fail('F005_NATIVE_GUARD_INVALID', 'native guard binaryを読めません', error));
  if (sha256(binary) !== F005_NATIVE_GUARD_PINS.outputBinarySha256) {
    return fail('F005_NATIVE_GUARD_INVALID', 'native guard binary pinが一致しません');
  }

  const guard = new NativeGuardProcess(executable);
  let closed = false;
  try {
    const hello = await guard.channel.command({ op: 'hello' });
    if (!hello.ok ||
      hello.abi !== F005_NATIVE_GUARD_PINS.abi ||
      hello.capacityAbi !== F005_NATIVE_GUARD_PINS.capacityAbi ||
      hello.rid !== F005_NATIVE_GUARD_PINS.rid ||
      hello.runtimeVersion !== F005_NATIVE_GUARD_PINS.runtimeVersion ||
      hello.binarySha256 !== F005_NATIVE_GUARD_PINS.outputBinarySha256 ||
      hello.workingDirectoryIsExecutableDirectory !== true) {
      return fail('F005_NATIVE_GUARD_INVALID', 'native guard ABI/toolchainが一致しません');
    }
    const synced = await guard.channel.command({
      op: 'sync-directory',
      root: workspace,
      relativePath: relativeDirectory,
    });
    if (!synced.ok || !exactKeys(synced, ['durability', 'ok']) ||
      synced.durability !== 'directory-flush-file-buffers') {
      const nativeCode = typeof synced.error === 'string'
        ? synced.error
        : 'DIRECTORY_SYNC_INVALID_REPLY';
      return fail(
        'F005_DIRECTORY_SYNC_FAILED',
        `native directory syncが${nativeCode}で停止しました`,
      );
    }
    await guard.close();
    closed = true;
  } catch (error) {
    if (error instanceof F005NativeCapacityError) throw error;
    return fail(
      'F005_DIRECTORY_SYNC_FAILED',
      'native directory syncを完了できません',
      error,
    );
  } finally {
    if (!closed) guard.terminate();
  }
}

interface GuardReply {
  readonly ok: boolean;
  readonly error?: string;
  readonly [key: string]: unknown;
}

interface NativeNotice {
  readonly noticeId: string;
  readonly sequence: number;
  readonly phase: F005CapacityPhase;
  readonly phaseInstanceId: string;
  readonly kind: 'create' | 'write' | 'rename' | 'delete';
  readonly path: string;
  readonly targetPath: string | null;
  readonly producerPid: number;
}

class JsonLineChannel {
  private readonly pending: Array<{
    readonly resolve: (value: GuardReply) => void;
    readonly reject: (error: Error) => void;
  }> = [];
  private ended = false;

  constructor(
    private readonly writeLine: (line: string) => void,
    onLine: (listener: (line: string) => void) => void,
    onFailure: (listener: (error: Error) => void) => void,
  ) {
    onLine((line) => {
      const current = this.pending.shift();
      if (!current) return;
      try {
        const parsed: unknown = JSON.parse(line);
        if (!record(parsed) || typeof parsed.ok !== 'boolean') {
          current.reject(new Error('guard response schema mismatch'));
        } else {
          current.resolve(parsed as GuardReply);
        }
      } catch (error) {
        current.reject(error as Error);
      }
    });
    onFailure((error) => {
      this.ended = true;
      for (const item of this.pending.splice(0)) item.reject(error);
    });
  }

  command(value: Readonly<Record<string, unknown>>): Promise<GuardReply> {
    if (this.ended) return Promise.reject(new Error('guard channel ended'));
    return new Promise<GuardReply>((resolveReply, reject) => {
      this.pending.push({ resolve: resolveReply, reject });
      try {
        this.writeLine(`${JSON.stringify(value)}\n`);
      } catch (error) {
        this.pending.pop();
        reject(error as Error);
      }
    });
  }

  end(error = new Error('guard channel ended')): void {
    this.ended = true;
    for (const item of this.pending.splice(0)) item.reject(error);
  }
}

class NativeGuardProcess {
  readonly process: ChildProcessWithoutNullStreams;
  readonly channel: JsonLineChannel;

  constructor(executable: string, args: readonly string[] = []) {
    let executableInfo: ReturnType<typeof lstatSync>;
    let binary: Buffer;
    try {
      executableInfo = lstatSync(executable);
      if (realpathSync.native(executable) !== executable ||
        !executableInfo.isFile() || executableInfo.isSymbolicLink() ||
        executableInfo.nlink !== 1) {
        throw new Error('native guard executable identity changed');
      }
      binary = readFileSync(executable);
    } catch (error) {
      throw fail(
        'F005_NATIVE_GUARD_INVALID',
        'spawn直前のnative guard実体検証に失敗しました',
        error,
      );
    }
    if (sha256(binary) !== F005_NATIVE_GUARD_PINS.outputBinarySha256) {
      throw fail(
        'F005_NATIVE_GUARD_INVALID',
        'spawn直前のnative guard binary pinが一致しません',
      );
    }
    this.process = spawn(executable, args, {
      cwd: dirname(executable),
      windowsHide: true,
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    const lines = createInterface({ input: this.process.stdout });
    this.channel = new JsonLineChannel(
      (line) => this.process.stdin.write(line),
      (listener) => lines.on('line', listener),
      (listener) => {
        this.process.once('error', listener);
        this.process.stderr.once('error', listener);
        this.process.once('exit', (code) => {
          if (code !== 0) listener(new Error(`native guard exited: ${String(code)}`));
        });
      },
    );
  }

  async close(): Promise<void> {
    if (this.process.exitCode !== null) {
      if (this.process.exitCode !== 0) {
        throw new Error(`native guard exited: ${String(this.process.exitCode)}`);
      }
      this.channel.end();
      return;
    }
    await new Promise<void>((resolveExit, reject) => {
      let settled = false;
      const cleanup = (): void => {
        this.process.off('exit', onExit);
        this.process.off('error', onError);
      };
      const onExit = (code: number | null): void => {
        if (settled) return;
        settled = true;
        cleanup();
        if (code === 0) resolveExit();
        else reject(new Error(`native guard exited: ${String(code)}`));
      };
      const onError = (error: Error): void => {
        if (settled) return;
        settled = true;
        cleanup();
        reject(error);
      };
      this.process.once('exit', onExit);
      this.process.once('error', onError);
      const observedExitCode = this.process.exitCode;
      if (observedExitCode !== null) {
        onExit(observedExitCode);
        return;
      }
      this.process.stdin.end();
    });
    this.channel.end();
  }

  terminate(): void {
    this.channel.end();
    this.process.kill();
  }

  async terminateAndWait(): Promise<void> {
    this.channel.end();
    if (this.process.exitCode !== null) return;
    await new Promise<void>((resolveExit, reject) => {
      const cleanup = (): void => {
        this.process.off('exit', onExit);
        this.process.off('error', onError);
      };
      const onExit = (): void => {
        cleanup();
        resolveExit();
      };
      const onError = (error: Error): void => {
        cleanup();
        reject(error);
      };
      this.process.once('exit', onExit);
      this.process.once('error', onError);
      if (!this.process.kill() && this.process.exitCode === null) {
        cleanup();
        reject(new Error('native guard termination failed'));
      } else if (this.process.exitCode !== null) {
        onExit();
      }
    });
  }
}

class NativePipeClient {
  readonly channel: JsonLineChannel;
  private readonly socket: Socket;
  private readonly lines: ReturnType<typeof createInterface>;

  private constructor(
    socket: Socket,
    readonly authToken: string,
    readonly sessionNonce: string,
  ) {
    this.socket = socket;
    this.lines = createInterface({ input: socket });
    this.channel = new JsonLineChannel(
      (line) => socket.write(line),
      (listener) => this.lines.on('line', listener),
      (listener) => {
        socket.once('error', listener);
        socket.once('close', () => listener(new Error('native pipe closed')));
      },
    );
  }

  static async connect(
    pipeName: string,
    authToken: string,
    sessionNonce: string,
  ): Promise<NativePipeClient> {
    if (!/^[a-z0-9-]{1,128}$/u.test(pipeName) ||
      !SHA256.test(authToken) || !SHA256.test(sessionNonce)) {
      return fail('F005_NATIVE_GUARD_INVALID', 'native pipe endpointが不正です');
    }
    const socket = createConnection(`\\\\.\\pipe\\${pipeName}`);
    await new Promise<void>((resolveConnect, reject) => {
      socket.once('connect', resolveConnect);
      socket.once('error', reject);
    });
    return new NativePipeClient(socket, authToken, sessionNonce);
  }

  async command(value: Readonly<Record<string, unknown>>): Promise<GuardReply> {
    const reply = await this.channel.command({
      ...value,
      authToken: this.authToken,
      sessionNonce: this.sessionNonce,
    });
    if (!reply.ok) {
      const code = typeof reply.error === 'string' ? reply.error : 'CAPACITY_GUARD_FAILURE';
      return fail(
        classifyF005NativeCapacityReplyError(code),
        `native capacity guardが${code}で停止しました`,
      );
    }
    return reply;
  }

  close(): void {
    this.lines.close();
    this.channel.end();
    this.socket.end();
  }
}

export interface F005NativeCapacitySessionOptions {
  readonly workspace: string;
  readonly owner: string;
  readonly workId: string;
  readonly candidateSha256: string;
  readonly executable?: string;
  readonly sessionNonce?: string;
  readonly onStartupFailure?: (code: F005NativeCapacityErrorCode) => Promise<void>;
}

export interface F005NativeCapacityCloseResult {
  readonly journalId: string;
  readonly journalPath: string;
  readonly journalSha256: string;
  readonly journal: CapacityJournalV3;
}

export interface F005NativeCapacitySession {
  readonly journalId: string;
  readonly journalPath: string;
  readonly owner: string;
  readonly workId: string;
  readonly candidateSha256: string;
  readonly sessionNonce: string;
  readonly workerPid: number;
  readonly voiceBackend: F005CapacityRecorderBackend;
  readonly acceptanceBackend: F005AcceptanceCapacityBackend;
  runInheritedWorker(
    executable: string,
    args: readonly string[],
    cwd: string,
  ): Promise<{ readonly pid: number; readonly exitCode: number }>;
  beginPhase(phase: F005CapacityPhase, workId: string | null, phaseInstanceId: string): Promise<void>;
  observeMutation(notice: {
    readonly noticeId: string;
    readonly sequence: number;
    readonly phase: F005CapacityPhase;
    readonly phaseInstanceId: string;
    readonly kind: 'create' | 'rename' | 'delete';
    readonly path: string;
    readonly targetPath: string | null;
    readonly sha256: string | null;
    readonly bytes: number;
  }): Promise<void>;
  endPhase(phase: F005CapacityPhase, phaseInstanceId: string): Promise<void>;
  close(): Promise<F005NativeCapacityCloseResult>;
  abort(): Promise<void>;
}

/**
 * production recorder factoryがtest fakeを解禁せず、実native sessionからmintされた
 * backendだけを識別するためのread-only判定。
 */
export function isMintedF005NativeCapacityBackend(value: unknown): boolean {
  return value !== null && typeof value === 'object' && mintedNativeBackends.has(value);
}

/**
 * 固定binaryを起動し、ETW権限確認後にJob・kernel FileIO・認証pipeを一体で開始する。
 * production fakeやfilesystem watcherへのfallbackは持たない。
 * @des DES-F005-006 DES-F005-012 @fun FUN-F005-047 @ut UT-F005-047
 */
export async function startF005NativeCapacitySession(
  options: F005NativeCapacitySessionOptions,
): Promise<F005NativeCapacitySession> {
  if (!isAbsolute(options.workspace) || resolve(options.workspace) !== options.workspace ||
    (options.executable !== undefined && (
      !isAbsolute(options.executable) ||
      resolve(options.executable) !== options.executable
    )) ||
    !safeString(options.owner) || options.owner.length > 256 ||
    !WORK_IDS.has(options.workId) || !SHA256.test(options.candidateSha256)) {
    return fail('F005_NATIVE_GUARD_INVALID', 'workspace/owner/work/candidateが不正です');
  }
  const sessionNonce = options.sessionNonce ?? randomBytes(32).toString('hex');
  if (!SHA256.test(sessionNonce)) {
    return fail('F005_NATIVE_GUARD_INVALID', 'session nonceが不正です');
  }
  const journalId = sha256(
    `${sessionNonce}\0${options.owner}\0${options.workId}\0${options.candidateSha256}\0f005-capacity-v3`,
  );
  const journalPath = `.cache/f005-capacity/${journalId}.json`;
  const executable = options.executable ??
    await resolveF005NativeGuardExecutable(options.workspace);
  const binary = await readFile(executable).catch((error) =>
    fail('F005_NATIVE_GUARD_INVALID', 'native guard binaryを読めません', error));
  if (sha256(binary) !== F005_NATIVE_GUARD_PINS.outputBinarySha256) {
    return fail('F005_NATIVE_GUARD_INVALID', 'native guard binary pinが一致しません');
  }

  let guard: NativeGuardProcess | undefined;
  let pipe: NativePipeClient | undefined;
  let startupStage:
    | 'guard-channel'
    | 'pipe-connect'
    | 'register-self'
    | 'probe-arm'
    | 'probe-write'
    | 'probe-verify' = 'guard-channel';
  try {
    guard = new NativeGuardProcess(executable);
    const activeGuard = guard;
    const hello = await activeGuard.channel.command({ op: 'hello' });
    if (!hello.ok ||
      hello.abi !== F005_NATIVE_GUARD_PINS.abi ||
      hello.capacityAbi !== F005_NATIVE_GUARD_PINS.capacityAbi ||
      hello.rid !== F005_NATIVE_GUARD_PINS.rid ||
      hello.runtimeVersion !== F005_NATIVE_GUARD_PINS.runtimeVersion ||
      hello.binarySha256 !== F005_NATIVE_GUARD_PINS.outputBinarySha256 ||
      hello.workingDirectoryIsExecutableDirectory !== true) {
      return fail('F005_NATIVE_GUARD_INVALID', 'native guard ABI/toolchainが一致しません');
    }
    const preflight = await activeGuard.channel.command({ op: 'capacity-preflight' });
    if (!preflight.ok) {
      const nativeCode = typeof preflight.error === 'string' ? preflight.error : 'ETW_PREFLIGHT_FAILED';
      return fail(
        nativeCode.startsWith('ETW_PRIVILEGE_REQUIRED')
          ? 'F005_ETW_PRIVILEGE_REQUIRED'
          : 'F005_NATIVE_GUARD_INVALID',
        `ETW preflightが${nativeCode}で停止しました`,
      );
    }
    const started = await activeGuard.channel.command({
      op: 'capacity-start',
      root: options.workspace,
      journalRelativePath: journalPath,
      owner: options.owner,
      sessionNonce,
      workId: options.workId,
      candidateSha256: options.candidateSha256,
    });
    if (!started.ok ||
      started.capacityAbi !== F005_NATIVE_GUARD_PINS.capacityAbi ||
      typeof started.pipeName !== 'string' ||
      typeof started.authToken !== 'string') {
      const nativeCode = typeof started.error === 'string' ? started.error : 'CAPACITY_START_FAILED';
      return fail(
        nativeCode.startsWith('ETW_PRIVILEGE_REQUIRED')
          ? 'F005_ETW_PRIVILEGE_REQUIRED'
          : 'F005_NATIVE_GUARD_INVALID',
        `native capacity sessionが${nativeCode}で停止しました`,
      );
    }
    startupStage = 'pipe-connect';
    pipe = await NativePipeClient.connect(started.pipeName, started.authToken, sessionNonce);
    startupStage = 'register-self';
    const registered = await pipe.command({ op: 'registerSelf' });
    const processIdentityProbePath = `.cache/f005-capacity/${journalId}.probe`;
    if (registered.pid !== process.pid ||
      registered.jobIdentity !== started.jobIdentity ||
      registered.processIdentityProbePath !== processIdentityProbePath) {
      return fail('F005_CAPACITY_IPC_FAILED', 'root workerのJob結合が不正です');
    }
    const absoluteProcessIdentityProbePath =
      join(options.workspace, ...processIdentityProbePath.split('/'));
    startupStage = 'probe-arm';
    const armedProbe = await pipe.command({
      op: 'armProcessIdentityProbe',
      path: processIdentityProbePath,
    });
    if (armedProbe.state !== 'armed' || armedProbe.path !== processIdentityProbePath) {
      return fail('F005_CAPACITY_IPC_FAILED', 'ETW process identity probeを開始できません');
    }
    try {
      startupStage = 'probe-write';
      await writeFile(
        absoluteProcessIdentityProbePath,
        randomBytes(32),
        { flag: 'wx' },
      );
      startupStage = 'probe-verify';
      const verifiedProbe = await pipe.command({
        op: 'verifyProcessIdentityProbe',
        path: processIdentityProbePath,
      });
      if (verifiedProbe.state !== 'verified' ||
        verifiedProbe.path !== processIdentityProbePath) {
        return fail('F005_CAPACITY_IPC_FAILED', 'ETW process identity probeを確認できません');
      }
    } finally {
      await unlink(absoluteProcessIdentityProbePath).catch(() => undefined);
    }

    let activePhase: {
      readonly phase: F005CapacityPhase;
      readonly workId: string | null;
      readonly phaseInstanceId: string;
    } | null = null;
    let nextApplicationNoticeSequence = 1;
    let lastNativeNoticeSequence = 0;
    let closed = false;
    const runInheritedWorker = async (
      executable: string,
      args: readonly string[],
      cwd: string,
    ): Promise<{ readonly pid: number; readonly exitCode: number }> => {
      const expectedEntry = join(options.workspace, 'scripts', 'build-offline.mjs');
      if (closed || activePhase?.phase !== 'build' ||
        activePhase.workId !== options.workId ||
        executable !== process.execPath || cwd !== options.workspace ||
        !Array.isArray(args) || args.length !== 1 || args[0] !== expectedEntry) {
        return fail('F005_CAPACITY_IPC_FAILED', 'inherited worker起動tupleが不正です');
      }
      const child = spawn(executable, [...args], {
        cwd,
        env: {
          ...process.env,
          npm_config_offline: 'true',
          npm_config_audit: 'false',
          npm_config_fund: 'false',
        },
        windowsHide: true,
        stdio: ['ignore', 'inherit', 'inherit'],
      });
      if (!child.pid) return fail('F005_CAPACITY_IPC_FAILED', 'inherited worker PIDを取得できません');
      const pid = child.pid;
      const exitCode = await new Promise<number>((resolveExit, reject) => {
        child.once('error', reject);
        child.once('exit', (code) =>
          code === null ? reject(new Error('inherited worker exit codeがありません')) : resolveExit(code));
      }).catch((error) =>
        fail('F005_CAPACITY_IPC_FAILED', 'inherited workerを完了できません', error));
      return Object.freeze({ pid, exitCode });
    };
    const beginPhase = async (
      phase: F005CapacityPhase,
      workId: string | null,
      phaseInstanceId: string,
    ): Promise<void> => {
      if (!PHASES.has(phase) || !SHA256.test(phaseInstanceId) ||
        workId !== options.workId) {
        return fail('F005_CAPACITY_IPC_FAILED', 'phase tupleが不正です');
      }
      await pipe?.command({ op: 'beginPhase', phase, workId, phaseInstanceId });
      activePhase = { phase, workId, phaseInstanceId };
      nextApplicationNoticeSequence = 1;
    };
    const endPhase = async (
      phase: F005CapacityPhase,
      phaseInstanceId: string,
    ): Promise<void> => {
      await pipe?.command({ op: 'endPhase', phase, phaseInstanceId });
      activePhase = null;
    };
    const observe = async (notice: NativeNotice): Promise<{
      readonly noticeId: string;
      readonly sessionNonce: string;
      readonly sequence: number;
      readonly workerPid: number;
      readonly matchedEtw: true;
    }> => {
      if (!SHA256.test(notice.noticeId) || !SHA256.test(notice.phaseInstanceId) ||
        !Number.isSafeInteger(notice.sequence) ||
        !Number.isSafeInteger(notice.producerPid) || notice.producerPid <= 0 ||
        notice.sequence !== nextApplicationNoticeSequence ||
        (notice.kind === 'rename' ? typeof notice.targetPath !== 'string' : notice.targetPath !== null)) {
        return fail('F005_CAPACITY_IPC_FAILED', 'mutation noticeが不正です');
      }
      if (!activePhase ||
        activePhase.phase !== notice.phase ||
        activePhase.phaseInstanceId !== notice.phaseInstanceId) {
        return fail('F005_CAPACITY_IPC_FAILED', 'active phaseとnoticeが一致しません');
      }
      const path = normalizeF005CapacityNoticePath(options.workspace, notice.path);
      const targetPath = notice.kind === 'rename'
        ? normalizeF005CapacityNoticePath(options.workspace, notice.targetPath)
        : null;
      const command = notice.kind === 'rename'
        ? {
            op: 'notice',
            noticeId: notice.noticeId,
            phase: notice.phase,
            workId: activePhase.workId,
            phaseInstanceId: notice.phaseInstanceId,
            producerPid: notice.producerPid,
            event: 'rename',
            from: path,
            to: targetPath,
          }
        : {
            op: 'notice',
            noticeId: notice.noticeId,
            phase: notice.phase,
            workId: activePhase.workId,
            phaseInstanceId: notice.phaseInstanceId,
            producerPid: notice.producerPid,
            event: notice.kind,
            path,
          };
      const reply = await pipe?.command(command);
      if (!reply || reply.state !== 'matched' ||
        reply.noticeSequence !== lastNativeNoticeSequence + 1 ||
        !Array.isArray(reply.observationSequences) ||
        reply.observationSequences.length === 0) {
        return fail('F005_CAPACITY_IPC_FAILED', 'noticeに対応するETW観測がありません');
      }
      lastNativeNoticeSequence = Number(reply.noticeSequence);
      nextApplicationNoticeSequence += 1;
      return Object.freeze({
        noticeId: notice.noticeId,
        sessionNonce,
        sequence: notice.sequence,
        workerPid: notice.producerPid,
        matchedEtw: true as const,
      });
    };
    const writeTemporary = async (
      path: string,
      bytes: Uint8Array,
      expectedSha256: string,
    ): Promise<F005TemporaryWriteLease> => {
      if (closed || activePhase?.phase !== 'voice' ||
        activePhase.workId !== options.workId ||
        !(bytes instanceof Uint8Array) ||
        bytes.byteLength === 0 || bytes.byteLength > 5_760_044 ||
        !SHA256.test(expectedSha256) ||
        sha256(bytes) !== expectedSha256) {
        return fail('F005_CAPACITY_IPC_FAILED', 'native write-through tupleが不正です');
      }
      const writePhase = activePhase;
      const relativePath = normalizeF005CapacityNoticePath(options.workspace, path);
      const writer = new NativeGuardProcess(
        executable,
        ['--write-through-once'],
      );
      try {
        const hello = await writer.channel.command({ op: 'hello' });
        if (!hello.ok || hello.abi !== F005_NATIVE_GUARD_PINS.abi ||
          hello.capacityAbi !== F005_NATIVE_GUARD_PINS.capacityAbi ||
          hello.rid !== F005_NATIVE_GUARD_PINS.rid ||
          hello.runtimeVersion !== F005_NATIVE_GUARD_PINS.runtimeVersion ||
          hello.binarySha256 !== F005_NATIVE_GUARD_PINS.outputBinarySha256 ||
          hello.workingDirectoryIsExecutableDirectory !== true ||
          !Number.isSafeInteger(hello.processId) || Number(hello.processId) <= 0 ||
          Number(hello.processId) !== writer.process.pid ||
          Number(hello.processId) === process.pid) {
          return fail('F005_NATIVE_GUARD_INVALID', 'write-through helper ABIが一致しません');
        }
        const producerPid = Number(hello.processId);
        const reserved = await pipe?.command({
          op: 'reserveWrite',
          phase: writePhase.phase,
          workId: writePhase.workId,
          phaseInstanceId: writePhase.phaseInstanceId,
          producerPid,
          path: relativePath,
        });
        if (!reserved || !reserved.ok || reserved.state !== 'reserved' ||
          reserved.path !== relativePath || reserved.producerPid !== producerPid) {
          return fail('F005_CAPACITY_IPC_FAILED', 'native write-through予約に失敗しました');
        }
        const reply = await writer.channel.command({
          op: 'write-through',
          root: options.workspace,
          relativePath,
          expectedSha256,
          bodyBase64: Buffer.from(bytes).toString('base64'),
        });
        if (!reply.ok ||
          reply.relativePath !== relativePath ||
          reply.bytes !== bytes.byteLength ||
          reply.sha256 !== expectedSha256 ||
          typeof reply.nativeIdentity !== 'string' ||
          !NATIVE_FILE_IDENTITY.test(reply.nativeIdentity) ||
          reply.durability !== 'file-flag-write-through-flush-file-buffers-delete-on-close') {
          const code = typeof reply.error === 'string' ? reply.error : 'WRITE_THROUGH_FAILED';
          return fail(
            classifyF005NativeWriteThroughReplyError(code),
            'native write-throughが固定failure categoryで停止しました',
          );
        }
        const nativeIdentity = reply.nativeIdentity as F005NativeFileIdentity;
        let currentRelativePath = relativePath;
        let settled = false;
        return Object.freeze({
          producerPid,
          nativeIdentity,
          rename: async (targetPath: string): Promise<void> => {
            if (settled) return fail('F005_CAPACITY_IPC_FAILED', 'write-through leaseは消費済みです');
            const relativeTarget = normalizeF005CapacityNoticePath(options.workspace, targetPath);
            const prepared = await pipe?.command({
              op: 'prepareWriteRename',
              phase: writePhase.phase,
              workId: writePhase.workId,
              phaseInstanceId: writePhase.phaseInstanceId,
              producerPid,
              from: currentRelativePath,
              to: relativeTarget,
            });
            if (!prepared || !prepared.ok || prepared.state !== 'rename-prepared' ||
              prepared.from !== currentRelativePath || prepared.to !== relativeTarget ||
              prepared.producerPid !== producerPid) {
              return fail('F005_CAPACITY_IPC_FAILED', 'native write-through rename予約に失敗しました');
            }
            const renamed = await writer.channel.command({
              op: 'write-rename',
              relativePath: currentRelativePath,
              relativeTarget,
              expectedSha256,
            });
            if (!renamed.ok || renamed.state !== 'renamed' ||
              renamed.relativePath !== relativeTarget ||
              renamed.sha256 !== expectedSha256 ||
              renamed.nativeIdentity !== nativeIdentity) {
              const code = typeof renamed.error === 'string'
                ? renamed.error
                : 'WRITE_THROUGH_RENAME_FAILED';
              return fail(
                classifyF005NativeWriteThroughReplyError(code),
                'native write-through renameが固定failure categoryで停止しました',
              );
            }
            currentRelativePath = relativeTarget;
          },
          commit: async (): Promise<void> => {
            if (settled) return fail('F005_CAPACITY_IPC_FAILED', 'write-through leaseは消費済みです');
            const prepared = await pipe?.command({
              op: 'prepareWriteCompletion',
              path: currentRelativePath,
              phase: writePhase.phase,
              phaseInstanceId: writePhase.phaseInstanceId,
              producerPid,
              workId: writePhase.workId,
            });
            if (!prepared ||
              Object.keys(prepared).sort().join(',') !== 'ok,sealSequence,state' ||
              prepared.ok !== true ||
              prepared.state !== 'completion-drain-prepared' ||
              !Number.isSafeInteger(prepared.sealSequence) ||
              Number(prepared.sealSequence) <= 0) {
              return fail(
                'F005_CAPACITY_IPC_FAILED',
                'write completion drainを準備できません',
              );
            }
            const committed = await writer.channel.command({
              op: 'write-commit',
              relativePath: currentRelativePath,
              expectedSha256,
            });
            if (!committed.ok || committed.state !== 'committed') {
              const code = typeof committed.error === 'string'
                ? committed.error
                : 'WRITE_THROUGH_COMMIT_FAILED';
              return fail(
                classifyF005NativeWriteThroughReplyError(code),
                'native write-through commitが固定failure categoryで停止しました',
              );
            }
            await writer.close();
            const completed = await pipe?.command({
              op: 'completeWrite',
              phase: writePhase.phase,
              workId: writePhase.workId,
              phaseInstanceId: writePhase.phaseInstanceId,
              producerPid,
              path: currentRelativePath,
            });
            if (!completed || !completed.ok || completed.state !== 'completed' ||
              completed.path !== currentRelativePath || completed.producerPid !== producerPid) {
              return fail('F005_CAPACITY_IPC_FAILED', 'native write-through予約を完了できません');
            }
            settled = true;
          },
          abort: async (): Promise<void> => {
            if (settled) return;
            try {
              const aborted = await writer.channel.command({ op: 'write-abort' });
              if (!aborted.ok || aborted.state !== 'aborted') {
                const code = typeof aborted.error === 'string'
                  ? aborted.error
                  : 'WRITE_THROUGH_ABORT_FAILED';
                return fail(
                  classifyF005NativeWriteThroughReplyError(code),
                  'native write-through abortが固定failure categoryで停止しました',
                );
              }
              await writer.close();
              settled = true;
            } catch (error) {
              await writer.terminateAndWait();
              return preserveF005NativeCapacityFailure(
                error,
                'native write-through abortを完了できません',
              );
            }
          },
        });
      } catch (error) {
        await writer.terminateAndWait();
        return preserveF005NativeCapacityFailure(
          error,
          'native write-through helperを完了できません',
        );
      }
    };

    const voiceBackend: F005CapacityRecorderBackend = Object.freeze({
      beginPhase,
      writeTemporary,
      observeMutation: (notice: F005MutationNotice): Promise<F005MutationObservation> =>
        observe(notice),
      endPhase,
    });
    const acceptanceBackend: F005AcceptanceCapacityBackend = Object.freeze({
      beginPhase,
      observeMutation: (
        notice: F005AcceptanceMutationNotice,
      ): Promise<F005AcceptanceMutationObservation> =>
        observe({
          noticeId: notice.noticeId,
          sequence: notice.sequence,
          phase: notice.phase,
          phaseInstanceId: notice.phaseInstanceId,
          kind: notice.kind === 'rename' ? 'rename' : notice.kind,
          path: notice.path,
          targetPath: notice.targetPath,
          producerPid: process.pid,
        }).then((observation) => Object.freeze({
          noticeId: notice.noticeId,
          sessionNonce: observation.sessionNonce as Sha256,
          sequence: observation.sequence,
          workerPid: observation.workerPid,
          matchedEtw: observation.matchedEtw,
        })),
      endPhase,
    });
    mintedNativeBackends.add(voiceBackend);
    mintedNativeBackends.add(acceptanceBackend);
    const close = async (): Promise<F005NativeCapacityCloseResult> => {
      if (closed) return fail('F005_CAPACITY_IPC_FAILED', 'capacity sessionは既に終了しています');
      const reply = await pipe?.command({ op: 'close' });
      if (!reply || typeof reply.journalSha256 !== 'string' ||
        !SHA256.test(reply.journalSha256)) {
        return fail('F005_CAPACITY_IPC_FAILED', 'closed journal応答が不正です');
      }
      const raw = await readFile(join(options.workspace, ...journalPath.split('/')), 'utf8');
      if (sha256(raw) !== reply.journalSha256) {
        return fail('F005_CAPACITY_JOURNAL_INVALID', 'journal実体SHAが応答と一致しません');
      }
      const journal = validateF005CapacityJournalV3(JSON.parse(raw) as unknown, true);
      if (journal.workId !== options.workId ||
        journal.candidateSha256 !== options.candidateSha256 ||
        journal.owner !== options.owner ||
        journal.sessionNonce !== sessionNonce) {
        return fail('F005_CAPACITY_JOURNAL_INVALID', 'journal開始tupleがsessionと一致しません');
      }
      closed = true;
      pipe?.close();
      await activeGuard.close();
      return Object.freeze({
        journalId,
        journalPath,
        journalSha256: reply.journalSha256,
        journal,
      });
    };
    const abort = async (): Promise<void> => {
      if (closed) return;
      closed = true;
      pipe?.close();
      activeGuard.terminate();
    };
    return Object.freeze({
      journalId,
      journalPath,
      owner: options.owner,
      workId: options.workId,
      candidateSha256: options.candidateSha256,
      sessionNonce,
      workerPid: process.pid,
      voiceBackend,
      acceptanceBackend,
      runInheritedWorker,
      beginPhase,
      observeMutation: async (
        notice: Parameters<F005NativeCapacitySession['observeMutation']>[0],
      ): Promise<void> => {
        await observe({ ...notice, producerPid: process.pid });
      },
      endPhase,
      close,
      abort,
    });
  } catch (error) {
    const failure = error instanceof F005NativeCapacityError
      ? error
      : new F005NativeCapacityError(
          startupStage === 'guard-channel'
            ? 'F005_NATIVE_GUARD_CHANNEL_FAILED'
            : startupStage === 'pipe-connect'
              ? 'F005_CAPACITY_IPC_CONNECT_FAILED'
              : startupStage === 'register-self'
                ? 'F005_CAPACITY_REGISTER_SELF_FAILED'
                : startupStage === 'probe-arm'
                  ? 'F005_CAPACITY_PROCESS_IDENTITY_PROBE_ARM_FAILED'
                  : startupStage === 'probe-write'
                    ? 'F005_CAPACITY_PROCESS_IDENTITY_PROBE_WRITE_FAILED'
                    : 'F005_CAPACITY_PROCESS_IDENTITY_PROBE_VERIFY_FAILED',
          'native capacity sessionの開始に失敗しました',
          { cause: error },
        );
    try {
      await options.onStartupFailure?.(failure.code);
    } catch {
      // 診断出力失敗でもcleanupと元の固定codeを優先する。
    }
    pipe?.close();
    guard?.terminate();
    throw failure;
  }
}

export interface CapacityJournalV3 {
  readonly schemaVersion: 3;
  readonly owner: string;
  readonly workId: string;
  readonly candidateSha256: string;
  readonly initialFreeBytes: number;
  readonly minimumObservedFreeBytes: number;
  readonly sessionNonce: string;
  readonly jobIdentity: string;
  readonly etwSessionIdentity: string;
  readonly peakLiveBytes: number;
  readonly registeredWorkerPids: readonly number[];
  readonly phases: readonly Record<string, unknown>[];
  readonly notices: readonly Record<string, unknown>[];
  readonly observations: readonly Record<string, unknown>[];
  readonly state: 'open' | 'closed';
  readonly closedSeal: Record<string, unknown> | null;
}

/**
 * nativeがdurable closeしたjournalをworkspace境界内から再読込し、canonical bytesと
 * 固定producer pinを検証する。actual容量へのbridgeはこの関数だけを入口にする。
 */
export async function readF005NativeCapacityJournalFile(
  workspace: string,
  journalPath: string,
): Promise<CapacityJournalV3> {
  if (!isAbsolute(workspace) || resolve(workspace) !== workspace ||
    !/^\.cache\/f005-capacity\/[0-9a-f]{64}\.json$/u.test(journalPath)) {
    return fail('F005_CAPACITY_JOURNAL_INVALID', 'native journal pathが不正です');
  }
  const lexicalPath = join(workspace, ...journalPath.split('/'));
  const [workspaceReal, journalReal, journalStat] = await Promise.all([
    realpath(workspace),
    realpath(lexicalPath),
    lstat(lexicalPath),
  ]).catch((error) => fail(
    'F005_CAPACITY_JOURNAL_INVALID',
    'native journal実体を検証できません',
    error,
  ));
  if (workspaceReal !== workspace || journalReal !== lexicalPath ||
    journalStat.isSymbolicLink() || !journalStat.isFile()) {
    return fail('F005_CAPACITY_JOURNAL_INVALID', 'native journal実体またはworkspace境界が不正です');
  }
  const raw = await readFile(lexicalPath, 'utf8')
    .catch((error) => fail(
      'F005_CAPACITY_JOURNAL_INVALID',
      'native closed journalを再読込できません',
      error,
    ));
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw) as unknown;
  } catch (error) {
    return fail('F005_CAPACITY_JOURNAL_INVALID', 'native journal JSONが不正です', error);
  }
  if (raw !== canonicalJson(parsed)) {
    return fail('F005_CAPACITY_JOURNAL_INVALID', 'native journalがcanonical bytesではありません');
  }
  return validateF005CapacityJournalV3(parsed, true);
}

/**
 * native journalを自己申告sealに依存せず再計算する。open journalは診断用にだけ
 * 読めるが、CapacityActualV3へ進める呼出しではrequireClosed=trueを必須とする。
 * @des DES-F005-006 DES-F005-012 @fun FUN-F005-019 FUN-F005-047 @ut UT-F005-019 UT-F005-047
 */
export function validateF005CapacityJournalV3(
  value: unknown,
  requireClosed = true,
): CapacityJournalV3 {
  if (!record(value) || !exactKeys(value, [
    'candidateSha256',
    'closedSeal',
    'etwSessionIdentity',
    'initialFreeBytes',
    'jobIdentity',
    'minimumObservedFreeBytes',
    'notices',
    'observations',
    'owner',
    'peakLiveBytes',
    'phases',
    'registeredWorkerPids',
    'schemaVersion',
    'sessionNonce',
    'state',
    'workId',
  ]) ||
    value.schemaVersion !== 3 ||
    !safeString(value.owner) ||
    !WORK_IDS.has(String(value.workId)) ||
    !SHA256.test(String(value.candidateSha256)) ||
    !safeInteger(value.initialFreeBytes) ||
    !safeInteger(value.minimumObservedFreeBytes) ||
    !safeInteger(value.peakLiveBytes) ||
    value.minimumObservedFreeBytes > value.initialFreeBytes ||
    !SHA256.test(String(value.sessionNonce)) ||
    !safeString(value.jobIdentity) ||
    !safeString(value.etwSessionIdentity) ||
    !Array.isArray(value.phases) ||
    !Array.isArray(value.registeredWorkerPids) ||
    value.registeredWorkerPids.some((pid) => !safeInteger(pid) || Number(pid) <= 0) ||
    value.registeredWorkerPids.some((pid, index, values) =>
      index > 0 && Number(values[index - 1]) >= Number(pid)) ||
    !Array.isArray(value.notices) ||
    !Array.isArray(value.observations) ||
    !['open', 'closed'].includes(String(value.state))) {
    return fail('F005_CAPACITY_JOURNAL_INVALID', 'CapacityJournalV3 schemaが不正です');
  }
  if (value.state === 'open') {
    if (value.closedSeal !== null || requireClosed) {
      return fail('F005_CAPACITY_JOURNAL_INVALID', 'open journalはactualへ使用できません');
    }
    return Object.freeze(value) as unknown as CapacityJournalV3;
  }
  if (!record(value.closedSeal) || !exactKeys(value.closedSeal, [
    'etwSequenceGapCount',
    'firstEtwSequence',
    'journalBodySha256',
    'lastEtwSequence',
    'producerBinarySha256',
  ]) ||
    value.closedSeal.etwSequenceGapCount !== 0 ||
    !safeInteger(value.closedSeal.firstEtwSequence) ||
    !safeInteger(value.closedSeal.lastEtwSequence) ||
    !SHA256.test(String(value.closedSeal.journalBodySha256)) ||
    value.closedSeal.producerBinarySha256 !== F005_NATIVE_GUARD_PINS.outputBinarySha256 ||
    value.registeredWorkerPids.length === 0) {
    return fail('F005_CAPACITY_JOURNAL_INVALID', 'closed sealが不正です');
  }

  const phaseInstances = new Map<string, { phase: string; workId: string | null; finished: boolean }>();
  for (const phaseRow of value.phases) {
    if (!record(phaseRow) || !exactKeys(phaseRow, [
      'freeBytes',
      'liveBytes',
      'observedAt',
      'phase',
      'phaseInstanceId',
      'state',
      'workId',
    ]) ||
      !PHASES.has(String(phaseRow.phase)) ||
      !SHA256.test(String(phaseRow.phaseInstanceId)) ||
      !['started', 'finished'].includes(String(phaseRow.state)) ||
      typeof phaseRow.observedAt !== 'string' ||
      !Number.isFinite(Date.parse(phaseRow.observedAt)) ||
      !safeInteger(phaseRow.liveBytes) ||
      !safeInteger(phaseRow.freeBytes) ||
      (phaseRow.workId !== null && !WORK_IDS.has(String(phaseRow.workId)))) {
      return fail('F005_CAPACITY_JOURNAL_INVALID', 'phase record列が不正です');
    }
    const id = String(phaseRow.phaseInstanceId);
    const existing = phaseInstances.get(id);
    if (phaseRow.state === 'started') {
      if (existing) return fail('F005_CAPACITY_JOURNAL_INVALID', 'phase instanceが再利用されています');
      phaseInstances.set(id, {
        phase: String(phaseRow.phase),
        workId: phaseRow.workId === null ? null : String(phaseRow.workId),
        finished: false,
      });
    } else {
      if (!existing || existing.finished ||
        existing.phase !== phaseRow.phase || existing.workId !== phaseRow.workId) {
        return fail('F005_CAPACITY_JOURNAL_INVALID', 'phase start/finish pairが不正です');
      }
      existing.finished = true;
    }
  }
  if (phaseInstances.size === 0 ||
    [...phaseInstances.values()].some((phase) => !phase.finished)) {
    return fail('F005_CAPACITY_JOURNAL_INVALID', 'phase recordが閉じていません');
  }

  const observationBySequence = new Map<number, Record<string, unknown>>();
  let expectedEtwSequence = 1;
  let recomputedPeak = 0;
  let recomputedMinimum = Number(value.initialFreeBytes);
  for (const observation of value.observations) {
    if (!record(observation)) {
      return fail('F005_CAPACITY_JOURNAL_INVALID', 'ETW observation列が不正です');
    }
    const event = String(observation.event);
    const expectedObservationKeys = event === 'rename'
      ? [
          'allocatedDeltaBytes', 'allocatedLengthBytes', 'etwSequence', 'event',
          'fileId128', 'freeBytesAvailable', 'freeBytesTotal', 'from', 'liveBytes',
          'logicalLengthBytes', 'noticeSequence', 'observedAt', 'phase',
          'phaseInstanceId', 'producer', 'producerBinarySha256', 'sha256', 'to',
          'volumeId', 'workId', 'workerPid',
        ]
      : [
          'allocatedDeltaBytes', 'allocatedLengthBytes', 'etwSequence', 'event',
          'fileId128', 'freeBytesAvailable', 'freeBytesTotal', 'liveBytes',
          'logicalLengthBytes', 'noticeSequence', 'observedAt', 'path', 'phase',
          'phaseInstanceId', 'producer', 'producerBinarySha256', 'sha256',
          'volumeId', 'workId', 'workerPid',
        ];
    const phaseBinding = phaseInstances.get(String(observation.phaseInstanceId));
    if (!exactKeys(observation, expectedObservationKeys) ||
      !safeInteger(observation.etwSequence) ||
      observation.etwSequence !== expectedEtwSequence++ ||
      !safeInteger(observation.workerPid) ||
      Number(observation.workerPid) <= 0 ||
      !value.registeredWorkerPids.includes(observation.workerPid) ||
      !PHASES.has(String(observation.phase)) ||
      !SHA256.test(String(observation.phaseInstanceId)) ||
      !safeInteger(observation.logicalLengthBytes) ||
      !safeInteger(observation.allocatedLengthBytes) ||
      !Number.isSafeInteger(observation.allocatedDeltaBytes) ||
      !safeInteger(observation.liveBytes) ||
      !safeInteger(observation.freeBytesAvailable) ||
      !safeInteger(observation.freeBytesTotal) ||
      Number(observation.freeBytesAvailable) > Number(observation.freeBytesTotal) ||
      !safeString(observation.volumeId) ||
      !safeString(observation.fileId128) ||
      typeof observation.observedAt !== 'string' ||
      !Number.isFinite(Date.parse(observation.observedAt)) ||
      (observation.noticeSequence !== null &&
        (!safeInteger(observation.noticeSequence) || Number(observation.noticeSequence) <= 0)) ||
      (observation.sha256 !== null && !SHA256.test(String(observation.sha256))) ||
      (observation.workId !== null && !WORK_IDS.has(String(observation.workId))) ||
      !phaseBinding ||
      phaseBinding.phase !== observation.phase ||
      phaseBinding.workId !== observation.workId ||
      observation.producer !== 'f005-native-guard' ||
      observation.producerBinarySha256 !== value.closedSeal.producerBinarySha256 ||
      !['create', 'write', 'setinfo', 'rename', 'delete'].includes(event) ||
      (event === 'rename'
        ? !safeRelativePath(observation.from) || !safeRelativePath(observation.to)
        : !safeRelativePath(observation.path))) {
      return fail('F005_CAPACITY_JOURNAL_INVALID', 'ETW observation列が不正です');
    }
    const sequence = Number(observation.etwSequence);
    observationBySequence.set(sequence, observation);
    recomputedPeak = Math.max(recomputedPeak, Number(observation.liveBytes));
    recomputedMinimum = Math.min(recomputedMinimum, Number(observation.freeBytesAvailable));
  }
  if (observationBySequence.size === 0 ||
    value.closedSeal.firstEtwSequence !== 1 ||
    value.closedSeal.lastEtwSequence !== observationBySequence.size ||
    value.peakLiveBytes !== recomputedPeak ||
    value.minimumObservedFreeBytes !== recomputedMinimum) {
    return fail('F005_CAPACITY_JOURNAL_INVALID', 'ETW sequenceまたは容量集計が不正です');
  }

  let expectedNoticeSequence = 1;
  const noticeIds = new Set<string>();
  const matchedObservationSequences = new Set<number>();
  for (const envelope of value.notices) {
    if (!record(envelope) || !exactKeys(envelope, [
      'notice',
      'noticeSequence',
      'observationSequences',
      'sessionNonce',
      'state',
      'workerPid',
    ]) ||
      envelope.sessionNonce !== value.sessionNonce ||
      envelope.noticeSequence !== expectedNoticeSequence++ ||
      envelope.state !== 'matched' ||
      !safeInteger(envelope.workerPid) ||
      !Array.isArray(envelope.observationSequences) ||
      envelope.observationSequences.length === 0 ||
      !record(envelope.notice) ||
      !SHA256.test(String(envelope.notice.noticeId)) ||
      noticeIds.has(String(envelope.notice.noticeId))) {
      return fail('F005_CAPACITY_JOURNAL_INVALID', 'notice envelope列が不正です');
    }
    const noticeEvent = String(envelope.notice.event);
    const expectedNoticeKeys = noticeEvent === 'rename'
      ? ['event', 'from', 'noticeId', 'phase', 'phaseInstanceId', 'to', 'workId']
      : ['event', 'noticeId', 'path', 'phase', 'phaseInstanceId', 'workId'];
    const phaseBinding = phaseInstances.get(String(envelope.notice.phaseInstanceId));
    if (!exactKeys(envelope.notice, expectedNoticeKeys) ||
      !['create', 'write', 'setinfo', 'rename', 'delete'].includes(noticeEvent) ||
      !PHASES.has(String(envelope.notice.phase)) ||
      !SHA256.test(String(envelope.notice.phaseInstanceId)) ||
      (envelope.notice.workId !== null && !WORK_IDS.has(String(envelope.notice.workId))) ||
      !phaseBinding ||
      phaseBinding.phase !== envelope.notice.phase ||
      phaseBinding.workId !== envelope.notice.workId ||
      (noticeEvent === 'rename'
        ? !safeRelativePath(envelope.notice.from) || !safeRelativePath(envelope.notice.to)
        : !safeRelativePath(envelope.notice.path))) {
      return fail('F005_CAPACITY_JOURNAL_INVALID', 'notice payload列が不正です');
    }
    noticeIds.add(String(envelope.notice.noticeId));
    for (const sequence of envelope.observationSequences) {
      const observation = observationBySequence.get(Number(sequence));
      if (!observation || matchedObservationSequences.has(Number(sequence)) ||
        observation.noticeSequence !== envelope.noticeSequence ||
        observation.workerPid !== envelope.workerPid ||
        observation.phase !== envelope.notice.phase ||
        observation.phaseInstanceId !== envelope.notice.phaseInstanceId ||
        observation.event !== envelope.notice.event ||
        (noticeEvent === 'rename'
          ? observation.from !== envelope.notice.from ||
            observation.to !== envelope.notice.to
          : observation.path !== envelope.notice.path)) {
        return fail('F005_CAPACITY_JOURNAL_INVALID', 'noticeとETW observationの結合が不正です');
      }
      matchedObservationSequences.add(Number(sequence));
    }
  }
  if ([...observationBySequence.values()].some((observation) =>
    observation.noticeSequence !== null &&
    !matchedObservationSequences.has(Number(observation.etwSequence)))) {
    return fail('F005_CAPACITY_JOURNAL_INVALID', 'notice付きETW observationが未結合です');
  }

  const body = Object.fromEntries(Object.entries(value)
    .filter(([key]) => key !== 'state' && key !== 'closedSeal'));
  if (sha256(canonicalJson(body)) !== value.closedSeal.journalBodySha256) {
    return fail('F005_CAPACITY_JOURNAL_INVALID', 'journal body sealが一致しません');
  }
  return Object.freeze(value) as unknown as CapacityJournalV3;
}
